### ISSUE TITLE
Incorrect coinbase lock height after wallet restore

### ISSUE THREAD

**Issue by jaspervdm** [mimblewimble/grin#1003]
I did a wallet restore for a wallet that has a decent amount of coinbase outputs. However I just noticed that all of them have a `lock_height` of 1000. Here is an example of an entry in the wallet.dat file:
```javascript
{
    "root_key_id": "fbfddadb09f614de72d3",
    "key_id": "13cdc709201299bc50c4",
    "n_child": 5310,
    "value": 60000000000,
    "status": "Unspent",
    "height": 41582,
    "lock_height": 1000,
    "is_coinbase": true,
    "block": "07d08e5d4785eefc9e00f2f2dab84f80d8e06642f8ab11a64289b14ab7f510a3",
    "merkle_proof": "..."
  },
```
A consequence of this is that a bunch of coinbase with less than 1000 confirmations are added to the spendable amount in the `grin wallet info`, even though they aren't actually spendable yet. 

I encountered the problem on the latest commit (8227ce9). I did a restore a couple of days ago and I believe the problem did not appear at that time, so my guess is a recent change broke something.

**Comment by yeastplume** [comment]
Should be fixed through: https://github.com/mimblewimble/grin/pull/1008 if you'd care to try it out

**Comment by jaspervdm** [comment]
I reran a restore with the latest commit. Indeed now the lock_height values are changed. The same entry now looks like this:
```
{
    "root_key_id": "fbfddadb09f614de72d3",
    "key_id": "13cdc709201299bc50c4",
    "n_child": 5310,
    "value": 60000000000,
    "status": "Unspent",
    "height": 41582,
    "lock_height": 45015,
    "is_coinbase": true,
    "block": "07d08e5d4785eefc9e00f2f2dab84f80d8e06642f8ab11a64289b14ab7f510a3",
    "merkle_proof": "..."
  }
```

I read #1008 but I'm not sure I understand. Couldn't the lock height be calculated from `height+1000`?

**Comment by yeastplume** [comment]
The lock height should be the current height (i.e. the height of the chain when you did the restore) + 1000, so that lock height looks correct. I don't know why "height" is showing up as 41582 there, it should be 44015 (I'll check, but can you confirm you've cut-paste the entire output and not just parts of it).. also the original restored version (before the change) wouldn't have had a merkle proof

**Comment by yeastplume** [comment]
I think that's okay now because you were running against an archival node.. when you first run wallet restore, it should populate height to current height, lock heights to current height+1000 and create a merkle proof for coinbase outputs. However, when you run `grin wallet info` the height will be updated with the actual height and block IF it exists on the server.. which will be the case for a full archival node, and for the last 3k or so blocks on a freshly fast-synced node.

In any case, the merkle proof is gone and needs to be regenerated on restore, so after restoring you'll still have a merkle proof that's only valid 1000 blocks after the restore.. so the lock height remains correct. I think all is okay here.

**Comment by jaspervdm** [comment]
Okay, thanks!
