### ISSUE TITLE
Cleanup: consolidate validation in `Block` and `Transaction`

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#1333]
We're at a point where there's enough common validation code between `Block` and `Transaction` to introduce a *thing* that both would include. The *thing* could have the `Vec`s of `Input`, `Output` and `Kernel` and all the validation in common.

Don't want to put the label `easy` on this, but should be fairly straightforward, except for a likely very large amount of changes for everything that uses the inputs/outputs/kernels directly from blocks and transactions. Also not sure whether introducing a trait would be useful (and doable) or a common struct would be fine.

**Comment by antiochp** [comment]
Just be aware I'm touching `tx.validate()` and `block.validate()` right now as part of https://github.com/mimblewimble/grin/issues/1327.
So conflicts here are likely.
Just a heads up.

**Comment by antiochp** [comment]
I think an internal struct of inputs|outputs|kernels might be the way to go here (at least the simplest).
"Composition over inheritance" https://en.wikipedia.org/wiki/Composition_over_inheritance


We need some flexibility in terms of max counts (see #1334 and #1336), specifically around building a block from a max size of tx (possibly from aggregating large number of smaller txs).
We need room in the block for the coinbase output(s) and kernel(s) in addition to those from the tx(s).

But if have an internal struct then it will likely make it easier to wrap a set of validation rules that can be run in isolation (block validation right now assumes we have access to current chain state and current sums).

This may make it easier to call these (reusable) validation rules during `read()` so we can check we do not exceed max size during deserialization of blocks and transactions.

**Comment by hashmap** [comment]
Apriori I'd like to try a combination of an internal struct (let's call it `StemCell` which grows into different types of domain objects like `Block`) and a trait which is implemented by this structure. Domain objects include `StemCell` and implement the trait mostly by delegating to the stem cell, but with flexibility to customize particular methods.

**Comment by antiochp** [comment]
One crazy thought (feel free to disregard or ignore this) - 

Transactions right now are nothing more than containers for inputs|outputs|kernels (plus a kernel offset).

What if instead of blocks consisting of vecs of inputs|outputs|kernels they simply held a _single_ transaction?
Then everything collapses down to tx aggregation.
Block building is a case of retrieving txs from the tx pool, aggregating them into a single tx and building the block from that tx (and we're already doing or can do most of that via the tx pool today).

A valid block is then a valid internal tx along with block specific validation rules.

We'd need to work out how to handle coinbase outputs and kernels in the block case but there are a variety of ways we could do that.

**Comment by hashmap** [comment]
Not crazy at all, I was expecting it actually when I started checking the code for the first time, I think it's in the spirit of MW and Grin's minimal approach. I retrospectively justified it as a node to the domain language and type system, like one may want to have type LastName, FirstName and don't deal with plain strings. Code would be in conflict with he language (of the project) because we distinguish between block and txs. 

However personally I'd love to try this lisp-ish approach where everything is a tx.

**Comment by ignopeverell** [comment]
Thought about it as well but the transaction offset is on the way. So I thought about the new struct for inputs|outputs|kernels instead that both tx and block can use. But if you have a more elegant idea, I'm all for it.
