### ISSUE TITLE
monitor_peers running every 1s?

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1413]
This was a recent build from `master`.
The logs are very noisy from `monitor_peers` running - 

```
Aug 23 22:18:41.256 DEBG monitor_peers: 0 connected (0 most_work). all 2 = 1 healthy + 0 banned + 1 defunct
Aug 23 22:18:41.256 DEBG monitor_peers: no preferred peers
Aug 23 22:18:41.256 DEBG monitor_peers: no dandelion relay updating
Aug 23 22:18:41.256 DEBG Could not update dandelion relay
Aug 23 22:18:42.256 DEBG monitor_peers: 0 connected (0 most_work). all 2 = 1 healthy + 0 banned + 1 defunct
Aug 23 22:18:42.256 DEBG monitor_peers: no preferred peers
Aug 23 22:18:42.256 DEBG monitor_peers: no dandelion relay updating
Aug 23 22:18:42.256 DEBG Could not update dandelion relay
Aug 23 22:18:43.260 DEBG monitor_peers: 0 connected (0 most_work). all 2 = 1 healthy + 0 banned + 1 defunct
Aug 23 22:18:43.260 DEBG monitor_peers: no preferred peers
Aug 23 22:18:43.260 DEBG monitor_peers: no dandelion relay updating
Aug 23 22:18:43.260 DEBG Could not update dandelion relay
Aug 23 22:18:44.261 DEBG monitor_peers: 0 connected (0 most_work). all 2 = 1 healthy + 0 banned + 1 defunct
Aug 23 22:18:44.261 DEBG monitor_peers: no preferred peers
Aug 23 22:18:44.262 DEBG monitor_peers: no dandelion relay updating
Aug 23 22:18:44.262 DEBG Could not update dandelion relay
Aug 23 22:18:45.266 DEBG monitor_peers: 0 connected (0 most_work). all 2 = 1 healthy + 0 banned + 1 defunct
Aug 23 22:18:45.267 DEBG monitor_peers: no preferred peers
Aug 23 22:18:45.267 DEBG monitor_peers: no dandelion relay updating
Aug 23 22:18:45.267 DEBG Could not update dandelion relay
```

**Comment by hashmap** [comment]
@antiochp Only if we have not enough peers. I introduced it here https://github.com/mimblewimble/grin/commit/7dd2888b71c37ce9aabca419577b9b1c23ff66c4#diff-5668c4851b422864764771097d4f1abeR63

We waited 20 seconds before even trying to get more peers. Unfortunately on startup we get 2 seed peers, which was not enough to start the sync, so we were just sitting and waiting for next attempt. Now we try to get peers as quick as possible  then we get back to 20 seconds schedule.

Unfortunately in our tests we never have enough peers, I think I'll tweak this part to work differently in test env. However it helped to find some interesting bugs, for example we could ban a peer, discover it from another peer and replace the old object with a new one (because the address is the same), in fact removing the ban unintentionally. Before this tweak we have never seen this because most test finish sub 20 seconds.

**Comment by antiochp** [comment]
No it makes a lot of sense for faster startup times on a "real" node.
This was on a dev env locally where I had only 2 nodes talking to each other.

Maybe we can exponentially backoff over time, start at 1s and backoff over time to every 30s or so?

**Comment by hashmap** [comment]
I planed to implement backoff, but 1 sec interval helps to find some obscure bugs

**Comment by antiochp** [comment]
:+1:
