### ISSUE TITLE
Allow resending a transaction

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#1450]
@gavinmcdermott and I built a transaction that was orphaned:

https://grinscan.net/block/c96ca190ed895398f34b9a6c9978c794e959832d8ba815982186e9bd337ffb87

If #58 was implemented, it wouldn't be an issue. But it's not. In addition it's generally not a bad idea to allow people to resubmit their transaction in case of unforeseen situations.

@yeastplume I'm not sure what the best option is for this. I was hoping the full tx binary would be in the txlogs but it's not. Should we add it?

**Comment by antiochp** [comment]
Why is that block showing a difficulty of `0` on grinscan?

**Comment by yeastplume** [comment]
I'm not sure what the best option is here either, particularly for automating the re-submission. 

For a very basic starter approach, we could store each transaction as a blob in the senders' wallet database so at least the user can re-submit after a while if necessary (and provide a re-post command in the wallet). Because the transaction log is there, it's easy for the wallet to detect when a particular transaction hasn't hit the chain, and ask the user if they want to resubmit after a set number of blocks. (Less than ideal in the command-line case since the check could only happen when the user runs the wallet, but could work quite well in the web and other client cases).

Longer-term, it looks like we need to explore an approach the conversation in #58 is moving towards, having the mempool keep an index of validated blocks to posted transactions and keep it around for a while (and deal with all of the edge cases that entails somehow).

**Comment by yeastplume** [comment]
I'd be of the opinion that it's the node's responsibility... if a transaction goes in and there's nothing wrong with it, the network should accept it. I don't think it's viable for a currency to have to tell users 'sorry, there was a fork so your transaction is invalid. Better luck next time'.

**Comment by kargakis** [comment]
+1 on making this the node's responsibility. It would suck to require users to rebuild transactions especially if they have gone back n forth via the offline method.

**Comment by antiochp** [comment]
The node definitely bears some of this responsibility (we should monitor the local txpool and aim to get txs out of there if they appear stuck).

But we wouldn't necessarily need to rebuild txs if the wallet stored the fully built tx.

I think there _may_ be an argument for the wallet to also share some of the responsibility - any node is free to reject any txs, so the wallet may want to assume retry may be necessary in some cases. Particularly with some unknowns around tx aggregation, edge cases where txs cannot be aggregated successfully and get dropped somewhere in the network.

Maybe there is "robustness in depth" here with re-broadcast of txs happening at a couple of different layers (as long as we keep traffic under control).

**Comment by ignopeverell** [comment]
As @antiochp mentioned, this is a belt and suspender type situation ("defense in depth" sounds better, but less picturesque). The belt is having the pool do the right thing (#58) and it should be enough to keep our pants up. But if it fails, without suspenders (saving the full tx), we're totally caught with our pants down of forcing the user to re-issue the transaction from scratch. And that has security implications as well. Besides, suspenders and a pocket protector make for a great style.

**Comment by yeastplume** [comment]
#1473 Addresses the original issue, so the transaction is stored and can be re-sent with the `wallet repost` command. So the suspenders are in place and the belt is tracked in #58
