### ISSUE TITLE
how many block equals "confirmed"?

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1467]
Bitcoin uses 6 confirmations by convention (I don't know if this is universal or even widely accepted as a convention or not).

Ethereum uses a higher number but block times are shorter. I don't think there is a widely accepted single value in Ethereum (something between 12 and 40 probably)?

ZCash discussion on this topic - https://github.com/zcash/zcash/issues/952

Our discussion on the (somewhat related) "coinbase maturity" rule - #1457.

Our current Grin wallet implementation in `testnet3` uses a value of 1, so we get spendable/testable outputs as quickly as possible.
This is probably a poor choice and something we should define, setting a reasonable default value in the wallet.

The Zcash discussion raises some interesting questions around height limits during a re-org/rollback, mining on high-latency networks like I2P etc.

**Comment by ignopeverell** [comment]
There's an older post from Vitalik Buterin about this as well:

https://blog.ethereum.org/2015/09/14/on-slow-and-fast-block-times/

This issue is also very relevant to #58, as we'll have to decide how long we keep transactions around to be able to fish them out in case of reorg.

If we take the 6 blocks (an hour) rule of bitcoin for reference, it seems that it should be the minimum value for us (because our 10x shorter block time). On the other hand, picking 60 blocks to match bitcoin is definitely overkill (see Vitalik's post). So we're left with something between 6 and 60, possibly closer to 6.

Beyond that, there are likely too many unknown variables to predict this accurately. What's the block propagation latency distribution and the orphan rate? What's the peering between miners like? Is the network prone to attacks? Is there enough overall hashpower? Which leaves us with the conclusion that picking this value should be empirical: what has practically been the longest orphaned chain that resulted in loss of transactions?

This doesn't help very much, we have no experience with our chain yet. So we should pick some value for now and keep in mind we will very likely need to adjust this. Personally, I'd start with 10.

**Comment by antiochp** [comment]
We're defaulting to 10 confirmations in the wallet now to treat an output as spendable.
