### ISSUE TITLE
Consider relaxing timestamp monotonicity

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#1486]
Most blockchains, Bitcoin included, require a new block's timestamp to be at least the median time past (MTP), which is the median of the timestamps of the preceding so many blocks (11 for bitcoin).

Since bitcoin propagates blocks as long as timestamps are not more than 2 hours in the future (relative to a node's local time), this allows miners to report their true local time even if the preceding block is timestamps in the future.

While Grin reduces the 2 hour allowance to only 12 minutes, it doesn't allow timestamps  to precede that of the previous block. At the same time, its difficulty retargeting already accounts for possible non-monotonicity as it picks timestamp medians near beginning and end of the retarget window. 
If we really wanted to stick to timestamp monotonicity, this complication could be entirely avoided.

**Comment by ignopeverell** [comment]
The reason for the rule is to provide more resistance to time warp attacks, especially in presence of a 51% attack. It's arguable as a block every second is still possible, but I guess that's better than 10 per seconds?

**Comment by tromp** [comment]
I fail to see how requiring timestamps to be at least the MTP allows for more timewarp attacks;
could you elaborate on that? It seems you can still do no better than just having 11 consecutive identical timestamps. Once you get those than there's no difference between >= MTP and >= previous timestamp.

**Comment by zawy12** [comment]
Use of MTP only prevents the [powLimit attack](https://github.com/zawy12/difficulty-algorithms/issues/30) which is a >50% selfish mining attack that can result in getting an unlimited number of blocks in 2*N*solvetime. BTC, LTC, BCH, Dash, Verge, and all their clones are vulnerable, but I have not seen it occur.  Digishield coins are not vulnerable because of the use of MTP.   gmaxwell is considering a limit on how far in the past and future timestamps can be in order to stop ArtForz's GeistGeld coin timestamp attack (the original "timewarp") which will also stop this powLimit attack on BTC.  LTC's plugging of that hole in a different way does not stop the powLimit attack.

Some people think >50% attacks are not relevant because they are not addressable, but > 50% attacks will almost never occur in any coin if the difficulty algorithm is optimal, but will occur on almost any coin where it is not. For example, the lack of an optimal algorithm in Zcash has resulted in 66% to 80% hashrate attacks about twice a day since it began, merely getting 30 to 50 blocks a day at a 30% discount compared to the other miners.  Almost no one notices or complains, so it's not hardly a problem.  Small coins with larger holes to >50% attacks will soon get severely attacked (difficulty is forced lower with timestamp manipulation, or difficulty is too slow to respond) until they either die (almost every Cryptonote and Monero clone that did not change it's difficulty algorithm) or fork to get a new algorithm.  A good DA can survive 10x to 50x hashrate attacks without a problem other than 1 to 3 slow blocks post-attack, discouraging the attacks from happening again.

Preventing timestamps from being older than previous timestamp prevents the need for the use of the MTP by preventing the powLimit attack and enabling more protection against the Zcash type of >50% attacks.

Switching to most recent block instead of MTP will make the response 6 blocks faster. There might be a slight oscillation in Zcash caused by the timestamps being 5 or 6 blocks behind the targets that are used in the difficulty calculation.   But this is required: the oscillations are worse if the 6 most recent targets are ignored.

BTW Zcash and BTC use MTP plus 1 second as the lowest possible timestamp. [@str4d tracked it down to the beginning of BTC.](https://github.com/monero-project/monero/issues/3717#issuecomment-385209929) No seems to have a justification for the +1 other than str4d pointing out there's [an equal sign in BTC at this line](https://github.com/bitcoin/bitcoin/blob/e071a3f6c06f41068ad17134189a4ac3073ef76b/main.cpp#L1206) that "requires" the +1, but including the equal sign seems arbitrary.  Absent that equal sign, it would not cause a problem in DA's that work in terms of target. Those working in terms of difficulty might end up with a divide by zero.   Zcash has an open issue "wish list" discussion about preventing 
older-than-previous-block timestamps **[here](https://github.com/zcash/zcash/issues/1889)**.

**Comment by tromp** [comment]
Grin also requires timestamps to increase by at least +1:

	if header.timestamp <= prev.timestamp && !global::is_automated_testing_mode() {

and right away needs to make an exception for testing. It makes more sense to me to have

	if header.timestamp < prev.timestamp {

and deal with the extremely unlikely case of having equal timestamp 60 blocks apart by
just taking a max(1, tsdiff) there.

If everyone is ok with timestamp monotonicity, then we can just simply our difficulty retargetting and strip out all MTP complications there...

**Comment by zawy12** [comment]
The possibility of zero timespan does not seem to bother grin's retargetting. But it could represent a problem if any timespan in is used in a denominator anywhere (not just retargetting) or a zero result cause some other problem. Fundamentally I don't see a problem either way (either allow zero increase in timestamp from previous or have +1 as minimum).  Maybe having a different timestamp on every block and increasing with block number could be useful in some "3rd party" app.

BTW, I posted issues about the powLimit attack to LTC, Dash, Verge, and BCH but there was zero response.

**Comment by ignopeverell** [comment]
@tromp We don't use MTP so I'm not sure what there is to strip out? I do like strict monotonicity, it's conceptually simple.

**Comment by tromp** [comment]
We use median of timestamps in the difficulty regargetting (see MEDIAN_TIME_WINDOW),
which serves absolutely no purpose with increasing timestamps...

Strict monotonicity for timestamps is like trying to duplicate the functionality of block height,
while forcing artifical adjustments in case a miner (or pool) does happen to find consecutive blocks within one second. So have to disagree with the conceptual simplicity...

**Comment by sesam** [comment]
could block height be used in place of timestamps? The part about relating difficulty to real world time is maybe possible to outsource somehow. If launch date (and later, checkpoint timestamps) are added to the source code, then is that enough to prevent difficulty weakening / withholding attacks?

Also, does grin have a year 2038 issue, and if not, then are we using to many bits for timestamps?

**Comment by yeastplume** [comment]
Is this still to be considered an active area of research for Grin, or can we consider the ship sailed here?

**Comment by tromp** [comment]
No, this is no longer of interest. The ship has sailed.

Btw, Grin has no year 2038 issue, as it uses 64-bit timestamps.
