### ISSUE TITLE
Save all debug log to file

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#165]
As we're going close to testnet, we'll have bug reports coming in. Some may be trivial, many will be tricky, including multi-node race conditions. Those may happen rarely and on different people's computers so asking to enable debug logs after the fact won't help that much.

At least as long as we're in testnet mode, all debug logs should be captured all the time into a file (possibly rolling).

**Comment by yeastplume** [comment]
Been thinking same for a while, will get onto it.

**Comment by yeastplume** [comment]
Was looking at this a while ago, and I think slog https://github.com/slog-rs/slog is the library to be using as it nicely separates log collection from output and seems flexible and scalable. But rather than just using an env-logger wrapper around it (which is an option), it's probably worth setting it up properly, even if it means replacing all of the log statements throughout the code.

**Comment by ignopeverell** [comment]
I'm okay with slog, thanks for looking into it. And nice nice is current log macros are easily sed-able.

**Comment by ignopeverell** [comment]
Done by @yeastplume
