### ISSUE TITLE
Better error handling with error-chain?

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#166]
Rust error handling with Result is pretty good, relatively, but one big drawback is stacktraces from the error origination are not captured. Stacktraces will only be captured at the time of panic, which can be several levels above where the error occurred.

The error-chain crate [1] solves this by instrumenting errors with macros and encapsulates useful error patterns. Evaluate the use of error-crate and migrate current error handling to it if appropriate.

[1] https://github.com/rust-lang-nursery/error-chain

**Comment by casey** [comment]
`failure` might also be good to check out as an error-chain alternative:

[github](https://github.com/withoutboats/failure)
[website](https://boats.gitlab.io/failure/)
[discussion](https://www.reddit.com/r/rust/comments/7b88qp/failure_a_new_error_management_story/)

It looks a little bit less opaque and more obvious than `error-chain`, in my opinion.

**Comment by dongcarl** [comment]
@ignopeverell @casey I want to get started on this. I know that `failure` is getting more and more popular, let's decide on one and I'll go ahead with refactoring.

**Comment by antiochp** [comment]
I'd say go for it with `failure` on a branch and we can take a look - is it possible to do this in a limited area of the codebase initially (just to see how it looks?)

**Comment by dongcarl** [comment]
@antiochp Will do with a limited set of files that makes sense and reference this ticket.

**Comment by sesam** [comment]
@dongcarl Is this also about doing less of .unwrap()?

According to https://users.rust-lang.org/t/to-unwrap-or-not-to-unwrap/10900/10 the right thing is to not .unwrap().
Is grin different? I'm thinking that maybe getting a panic! quickly because of an .unwrap() is  a benefit in grin sometimes.

**Comment by ignopeverell** [comment]
Right, for non-recoverable situations, panicking is the best thing to do. I think it would still be better to rely on `expect` instead of `unwrap` to have at least a minimal message.

**Comment by dongcarl** [comment]
Busy with other things right now, so if someone else has got more time, go right ahead!

**Comment by Derzouli** [comment]
Hello guys, I'm new in these project, and I want to start this ticket. =)
I start working on it. Which limited set of files are related to this issue?

**Comment by sesam** [comment]
@Derzouli check the links above (https://github.com/mimblewimble/grin/issues/166#issuecomment-342335105) and then pick some part of grin to try and apply `failure` to.

I wanted to suggest some limited set of files that aren't being updated all the time (so you'd have less merge/rebase work) but recently it seems everything has started moving! :) Maybe pick https://github.com/mimblewimble/grin/tree/master/wallet/src to start with, and you could improve error message wording to make it more user friendly (and keep any relevant technical keywords in parantheses).

I saw https://github.com/mimblewimble/grin/tree/master/pow/src is a month since last change, but not much error handling in there for you to work with.

**Comment by yeastplume** [comment]
We're using Failure in the wallet and API code which seems to be working okay. Investigation is done for now so we can open separate issues to address specific error concerns.
