### ISSUE TITLE
core dump when starting grin with little memory free

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#1685]
A 16GB machine without swap partition can core dump on starting up grin (as I noted in #1683) due to a failed allocation of 8GB (!) of memory. The core dump also got my terminal into a strange state due to crashing out of `curses` without proper terminal state clean up, and even `reset` didn't help.

If possible, we should catch this and close down curses and explain the error, something like "get your machine some more RAM or swap space, or try turning it off and on again"

**Comment by elima** [comment]
I'm experiencing this issue 100% of times on my laptop, which has 16G RAM plus 16G swap. The grin server aborts right after syncing with the network, with the message:
```
memory allocation of 68719476736 bytes failed
```
It is trying to allocate exactly 64GB of RAM, which most likely you don't have unless this software is only intended to run on dedicated servers only. My guess is that it is trying to allocate 8GB per core (my laptop has 4 cores with hyperthreading).

This happens both with mining enabled or disabled.

I'm inclined to consider this issue a bug instead of an enhancement.

Thanks for developing grin. Looks quite an interesting project and I look forward to give it a try.

**Comment by ignopeverell** [comment]
Plenty of people (including myself) have Grin running on low performance environments, with 2GB of RAM. Anything special about what you're doing or your environment?

**Comment by yeastplume** [comment]
Closed for now until further detail is provided
