### ISSUE TITLE
ask for txhashset at 90% of horizon?

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1892]
In PR https://github.com/mimblewimble/grin/pull/1721, we have change the `horizon` from 48 hours to 1 week (i.e.  from 2880 to 10080).

So, for initial `BodySync` stage, we need download 90% * horizon  (i.e.  9072 full blocks), but before this change we only download 2592 blocks.

Is it safe to change this `90%` to for example `30%` here?  or something else, for faster sync.

```
DEBUG grin_servers::grin::sync::state_sync - fast_sync: before txhashset request, header head: 18460 / 058c207d, txhashset_head: 9387 / 052fc3fc
```

https://github.com/mimblewimble/grin/blob/b4ee1e14a435c33c3e1e30c4be7a99a87ba07a0a/servers/src/grin/sync/state_sync.rs#L147-L153

**Comment by ignopeverell** [comment]
Possibly, but then we need to think of what happens if there's a long reorg before the node had time to complete its history to get up to horizon.

A just-sync'd node will have a history that's more recent than horizon. It's temporary because as it reaches the head and gets blocks through gossip, it will complete its history fairly quickly. The reason for this is it takes some time to download and validate the state and we don't want our just-downloaded state to be older than horizon by the time we're done.

Now if the newly sync'd node is just missing 50 blocks after horizon, it's not a huge deal, the chances that a week-minus-50-blocks long reorg happens in the next hour is slim-to-none. If we extend that however, the risk increases. So we would need to make the code that decides to go into redoing the full sync including state on reorgs older than horizon use whatever our oldest state is at instead. May not be a bad thing to do regardless.

**Comment by garyyu** [comment]
Close this one since most of related discussions are in PR: #1902
