### ISSUE TITLE
Build system investigation

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#190]
Right now, everyone who wants to try out Grin needs to install an entire build environment, but sooner or later (probably sooner) it would be preferable to have a build system on top that produces packages that can be installed via package managers. Off the top of my head, initial targets would probably be something like:

-.deb for debian based systems (debian, ubuntu)
-arch linux AUR package
-.rpm files for redhat/centos
-mac .pkg (though this requires mac developer certs which have to be owned by somebody)
-Docker images (my thoughts is this should be parented to a base arch linux image arch tends to be up to date and have the least amount of cruft in a fresh install)

Cargo does a lot, but it doesn't do everything, and so some research is needed to select the appropriate tooling here. Whatever system is selected, it should play nicely with cargo and CI, producing nightly and tagged builds.

Also some consideration needed around mining plugins, how they're built and distributed, as some of them depend on a CUDA environment being available.

**Comment by edbo** [comment]
I've been following the project for a bit now and with the release of the testnet wanted to actually try out setting up a small network myself. My ideal way of doing this would be to create a Dockerfile and docker-compose.yml file that in a single command can create yourself a contained local regtest network but also a container to try out with testnet. If this is desirable I'm happy to map out a brief plan in a separate docker ticket.

FYI: My preference for CI tools is something completely within containers so you can make them reproducible and (mostly) portable between CI tools (there are a bunch now that are Docker native like Circle CI, Codeship etc...).

**Comment by ignopeverell** [comment]
Have a look at the "botnet" that @yeastplume setup:

https://github.com/mimblewimble/grin-docker/tree/master/botnet

It's very similar to what you described.

**Comment by ignopeverell** [comment]
Sorry didn't mean to close.

**Comment by edbo** [comment]
Nice! Thanks for the link up, will poke around.

**Comment by kargakis** [comment]
It would be nice to distribute ARM binaries/images too

**Comment by sesam** [comment]
Without volunteer package maintainers or multiple platforms, we could start off with either of
 - https://en.wikipedia.org/wiki/Flatpak keeps apps sandboxed which might be a good idea before grin has been properly tested and fuzzed for remote vulns.
 - https://en.wikipedia.org/wiki/AppImage allows users to install software without them needing to have root privileges
 - We should avoid https://snapcraft.io/ due to complexity, less cross-platform (depends on systemd, ignores preexisting solutions - NIH!)

Windows has https://chocolatey.org/ -- but we might want to minimize the learning curve and just distribute .exe + .gpg files for windows users.

For ARM, those with access to install ELF binaries on any ARM cpu are already very technical. The goal here is likely about making it very easy for those power users to cross compile. Maybe a [multi-stage Docker](https://docs.docker.com/develop/develop-images/multistage-build/) setup that spits out binaries, and some volunteer (@hendi?) to run the docker images on every new release tag. Possibly compare with [example from perkeep contribs](https://github.com/jhillyerd/perkeep-docker)
