### ISSUE TITLE
Aggsig contexts stored in the clear in LMDB

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#1988]
`save_private_context` and `get_private context` in the LMDB wallet directly store aggsig context objects, which store associated private keys in the clear. Large security hole as there's nothing otherwise stopping another process from reading those keys from LMDB. At a minimum, this should be changed to store the BIP32 derivation paths instead.

**Comment by jakecraige** [comment]
I have some interest in picking this up but would need some support on what's the right data to store and how to use it later to reinitialize the context appropriately. Here's what I've found so far:

The values we don't want to store are here:
https://github.com/mimblewimble/grin/blob/d5c3e61cbee3cec74da1274e8703aa9e5bb00b64/wallet/src/libwallet/types.rs#L357-L360 

And they are stored by default with serde. So by adding the [skip](https://serde.rs/attr-skip-serializing.html) annotation we can easily have it not write those. But then we need a way to get those back later which seems like the issue this issue is supposed to correct. **Let me know if those aren't the correct values we're trying to remove from the DB.**

To solve this you recommend (at minimum) to store the BIP32 paths instead. From what I've found so far, objects that are an [`Identifier` can be turned into a path](https://github.com/mimblewimble/grin/blob/d5c3e61cbee3cec74da1274e8703aa9e5bb00b64/keychain/src/types.rs#L125), so there may be an identifier somewhere we need to persist?

I figure there may be some information around where we initialize the context that this refers to.

https://github.com/mimblewimble/grin/blob/d5c3e61cbee3cec74da1274e8703aa9e5bb00b64/wallet/src/libwallet/internal/selection.rs#L78-L81

There is a `parent_key_id` available which is used as the account to select outputs from which seems like it could be useful here. Though I don't know if it actually is, and if so how that relates to the `sec_key` and `sec_nonce` which both, at least directly, don't use that value. And it's already stored alongside output data [a few lines down](https://github.com/mimblewimble/grin/blob/d5c3e61cbee3cec74da1274e8703aa9e5bb00b64/wallet/src/libwallet/internal/selection.rs#L124). 

Would you or someone be able to provide some guidance on what needs to be stored here and how we might go from that to reinitializing those values?

Thanks!

**Comment by yeastplume** [comment]
I don't think you need to mess with serde annotations, all that really needs to happen for the sec_key is that the struct needs to be changed to use/store the identifier used to derive the sec_key, and when it's needed re-derived the actual key from the identifier and (already loaded) master key.

Will have to think a bit more about the nonce, because if I remember correctly it's not derived from the master key, but from the underlying libsecp256k lib in order to ensure it's compatible with aggsig. It might be worth focusing on the sec_key and we can worry about the nonce separately

**Comment by jakecraige** [comment]
Sounds good, I'll take a look at just handling the sec_key to start

**Comment by yeastplume** [comment]
Resolved by #2189
