### ISSUE TITLE
Cut-through in transaction pools

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#201]
Allow for cut-through to append before transactions are included in a block. The difficulty is to resolve (or avoid) conflicts when the same transaction gets cut-through in 2 different ways by 2 different peers.

**Comment by antiochp** [comment]
What's the benefit of doing this in the transaction pool rather than letting this happen during block compaction?
Is it that we have the opportunity to do this across a potentially larger set of txns (miner may not select txs that can cut-through)?
Or to have the opportunity to reduce the pool size?

**Comment by ignopeverell** [comment]
There is no scalability gain, but there's a significant privacy gain as we end up with a non-interactive coinjoin with cut-through.

**Comment by quentinlesceller** [comment]
Fixed by https://github.com/mimblewimble/grin/pull/1067 👍
