### ISSUE TITLE
kernel features

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#2060]
Some notes from grin/dev conversation:

John Tromp @tromp 21:43
in fact, if miner not only has coinbase, but also regular tx in block, then he could combine kernels into one
so notion of coinbase kernel makes no sense?!

John Tromp @tromp
we shld get rid of coinbase flags in kernels though
and include kernel features in kernel_sig_msg
maybe it should be kernel_type rather than just a set of bits
256 different types offers more flexibility than 8 orthogonal features

David Burkett @DavidBurkett 23:53
Yep, I agree

John Tromp @tromp 23:55
we only have two types now; plain and (absolute) height locked; only latter needs to provide lock height
after launch we'll need to add type relative height locked, which will require kernel reference and height offset in message
that would be more awkward with feature bits

**Comment by tromp** [comment]
TxKernel has the field
	/// Options for a kernel's structure or use
	pub features: KernelFeatures,

Function kernel_sig_msg should write this field so that any signature commits to the features.
Right now the features only indicates whether the kernel belongs to a/the coinbase, which
in my view is unnecessary and undesirable. Instead, the feature should distinguish among:

1) a plain kernel
2) an absolute height locked kernel
3) (in future) a relative (to another kernel) height locked kernel

and the contents of kernel_sig_msg should depend on this.
There's no need to waste 8 bytes of a lock height in case 1).

**Comment by ignopeverell** [comment]
Makes a lot of sense on why the features should be included in the message to be signed, thanks for clarifying. We might need another T4 hard fork for this. Or perhaps just roll it out around release?

I do disagree regarding the necessity (or lack thereof) of the coinbase feature. Without it, we can't check the coinbase sums in isolation. And that's necessary so that miners can't circumvent maturity by making their coinbase a regular output (or do a 1 grin coinbase output and 59 grins regular output say). And maturity is necessary to avoid short reorg double-spend type attacks from miners.

**Comment by tromp** [comment]
Thanks for reminding me why coinbase kernel type is needed.

So that gives 4 types, including

0. a coinbase kernel
