### ISSUE TITLE
Create first launch wizard

### ISSUE THREAD

**Issue by hashmap** [mimblewimble/grin#2063]
Ask a user what is a purpose of this node:
1. Just a node
2. Node and wallet
3. Node, wallet and mining support 

Generate config. There should be ability to auto start wallet (will open a separate issue for that). Make sure that `api-token` is set correctly in the wallet config and explain a user how to configure it in the miner.

Currently the default is 1 which is actually not what the most users want.

**Comment by ignopeverell** [comment]
Won't 99% of users want 2 on mainnet?

**Comment by DavidBurkett** [comment]
Do we also want a checkbox (defaulted off) or something for 'full history/archive'? I feel like we should make that option fairly easy to choose, since users who want that option help support other archive nodes to sync.

**Comment by lehnberg** [comment]
If there's a strong majority (think >75%) for one option, and the other two options are considered 'advanced' use cases, then I would think that this one option should definitely be the default, letting the advanced users tinker and tweak as required to satisfy their needs.

The less friction for the most general user, the better, and we shouldn't ask them any questions we already know the answer to.

**Comment by DavidBurkett** [comment]
I'm not sure I agree. Just because it's an 'advanced' use case, doesn't necessarily mean they're an advanced user who wants to read all the docs to know what values to set in a big configuration file. I'm sure a decent number of people are going to want to try to mine grin, and I'm not sure they should all be considered 'advanced' users. Ideally they would be, so they know how to tweak everything for the best experience, but that doesn't mean they should be required to. We ought to try our best to make setting everything up as convenient as possible, as long as we try to minimize inconvenience for typical use cases.

**Comment by sesam** [comment]
Asking less is nicer. Specifically archiving is maybe only relevant for
pool services and long running nodes, and it's likely better that regular
nodes don't start archiving, then delete and un-/reinstall.

Wallet or not - until light wallets become hardened, 2 should be default to
maximize testing of grin's official wallet.

my 0.02G :)

**Comment by ignopeverell** [comment]
I don't think @lehnberg was saying we should purposefully make the other use cases harder either... I'd be happy with 2 being the default, 1 being a different and minimal binary, and then work on 3 being easier. Mining setups vary a lot so 3 is likely to require more flexibility (miner and wallet on same machine, multiple miners single wallet, etc.). I would be unhappy with having the wallet and the node sit in the same memory space (same process).
