### ISSUE TITLE
Set mainnet initial difficulty

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#2121]
We should start from assuming N 1080ti-like graphic cards and derive difficulty and secondary scaling from N. We may also need the number of high-memory graphic cards for the primary PoW until ASICs are developed. If we were to assume 100% hashpower on the AR PoW, I think we'd have:

```
d = 60/42 * N * 4 * 2^(29-26)*29
```

Did I get something wrong @tromp?

We could start with that and just set the scaling factor to 1. Then we can argue about values for N. From past discussions, it seems that a reasonable (high) range would be between 10k to 100k.

**Comment by tromp** [comment]
I think the natural initial ar_scale is just the weight of a 2^29 edge graph, which is 2^(1+29-24)*29 = 1856.
Let's say one 1080 Ti runs at 5 GPS (some minor optimizations will no doubt be found, so this is somewhat conservative). Then it finds 5 * 60 / 42 solutions per minute. So a good setting is
d = N  *  5 * 60 / 42  *  2^6 * 29.

I would optimistically assume that N overflows a short:-)

**Comment by ignopeverell** [comment]
I always get the base factor wrong (24 instead of 26), thanks. And good point on picking a slightly higher GPS. No objection on setting this the scaling factor to 1 to start with?

**Comment by tromp** [comment]
Oh yes, absolutely agree then.

**Comment by tromp** [comment]
Btw, there are apparently around 75K GPUs mining Cuckoo on Aeternity.
Of course only a fraction of these have the 7 GB required for Grin GPU mining.
But it's safe to assume that Grin can attract more hashpower than Aeternity.

**Comment by gunray88** [comment]
From a miner's perspective: The reason there are about 50k of 1080ti (and increasing, but it took a week to get there after introducing pools) worth currently mining at Aeternity is because there is a void to be filled untill the mining profits settle to market average. Aeternity blockchain produces about $90k worth of coins daily (based on current AE erc20 token trading price), which could, market-wise, fit about 180k worth of 1080tis to match the current daily mining revenue of $0.5 per 1080ti (ETH or about market average). This is the no1 reason it attracts as many GPUs - by simple market forces moving them there. They are attracted to profits above market average.

It would be safe to assume that Grin would attract more hashpower than Aeternity should they both be starting from scratch to a market that's yet to be made, but its a different case.

Anyway, even if you do set the difficulty too high, I suppose it would retarget quickly enough. I just wouldn't expect insta-mine situation with gauging it at "just" 10k worth of 1080tis. Going much higher could just make it a one very slow first block :).

Eager to start mining!

**Comment by jaspervdm** [comment]
Setting the initial difficulty too high is a pretty safe strategy. Even if we overestimate the hashing power by a few 100x, we only delay the first block by a couple of hours. In contrast, if we underestimate it there will be an instamine for the first blocks, which is a situation we would like to prevent.

**Comment by tromp** [comment]
in today's conversation:

John Tromp @tromp Jan 03 22:34
there are up to 5M 6+GB GPUs active in crypto mining
each getting 2 GPS on cuckaroo29
so rough upper limit is 10M GPS

Yeastplume @yeastplume Jan 03 22:36
very theoretical upper limit, yes

John Tromp @tromp Jan 03 22:36
question is if we shld aim for that hashrate to give 1 min block at launch
if 1 min for 10M GPS then diff0 = 1856 *10^7 * 60 / 42
that's 26.5 * 10^9

Yeastplume @yeastplume Jan 03 22:42
This is assuming every 6+GB GPU in the crypto-world jumps onto grin at launch?

John Tromp @tromp Jan 03 22:43
no, assumes a fraction 1/N of all eligible GPUs joins launch and first block has to wait N mins
so absolutely guarantees we cannot average sub minute blocks at launch

Yeastplume @yeastplume Jan 03 22:45
okay, got it

John Tromp @tromp Jan 03 22:45
N is somewhere between 1 and 100

Yeastplume @yeastplume Jan 03 22:48
If we assume beam numbers we'd say 2% of said GPUs are joining in

John Tromp @tromp Jan 03 22:48
interest in grin is bound to be substantially higher
i expect at least 10%

Yeastplume @yeastplume Jan 03 22:50
right, so 500k GPUs, 1/10

John Tromp @tromp Jan 03 22:51
so it looks extremely unlikely we'd have to wait for hours for first block

Yeastplume @yeastplume Jan 03 22:51
unless we want to over-estimate some more

John Tromp @tromp Jan 03 22:57
if we set diff0 = 2^24 * weight(29) then we have guaranteed 6 leading 0s for C29 cyclehash
that's only a little higher than above
2^24 * weight(31) is over 4 times higher still
another poll?

**Comment by GandalfThePink** [comment]
By setting the initial difficulty we are in fact making a prediction of the price for the grin tokens. Miners are acting out of financial incentive and if the price of grin is perceived lower than the electricity only few people will mine. 

I think there is a risk of overestimating the difficulty, which could leave few people having to burn through the initial difficulty. And in that case no commercial miner would help since the financial incentive is just not there. They will only join later when the difficulty has adjusted. 

I think it is more reasonable to take the testnet peak. That should be an honest estimate of all the people that are involved in the project. I would not expect that the initial hashrate is orders of magnitude larger than this and as long as it grows gradually there is no problem.

**Comment by jaspervdm** [comment]
Miners that will mine from launch are essentially speculators.

> And in that case no commercial miner would help since the financial incentive is just not there. They will only join later when the difficulty has adjusted.

What is the problem with this? Difficulty will adjust relatively quickly (counted in blocks). I think underestimating the graphrate is more harmful since it will result in effective instamine.

> I think it is more reasonable to take the testnet peak. 

This would underestimate the graphrate by orders of magnitude. For comparison, just look at the number of GPU's currently mining Beam.

**Comment by sesam** [comment]
:+1: prefer to overestimate

**Comment by BravoIndia** [comment]
He means no more than 100 minutes, if difficulty is set to 100x peak testnet rate, and assuming launch GPS is at least equivalent to peak testnet GPS--which is obviously a pretty safe assumption.

I thought the 10k - 1mln GPU estimate brought up on gitter was reasonable. 500k does seem on the high end to me as well, considering all these GPUs will have to be configured properly within the 30 minutes after genesis in order to try and mine in under 1min. I think 100k is very safe and reasonable, and still we'll probably see the first block take at least an hour, the difficulty decreasing, and then as more and more miners pile in as the first 24h unfold, the difficulty going back up.

**Comment by ignopeverell** [comment]
Not sure why that even needs to be said but any mainnet estimate below 50k cards is just silly. By comparison, I don't think a testnet has ever seen much more than 50 cards.

We've gone through a lot of pain and efforts to do everything above board so far, it's not to launch with a too low difficulty inviting speculations of instamine. As the person issuing the genesis block, it's a moral hazard I don't want.

**Comment by BravoIndia** [comment]
Fair enough @ignopeverell

**Comment by ignopeverell** [comment]
Fixed by #2379
