### ISSUE TITLE
A Short Message in Genesis Block of Mainnet

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#2143]
We don't need repeat what Satoshi Nakamoto did in Jan. 2009 for his/her Bitcoin Genesis block:
> **The Times 03/Jan/2009 Chancellor on brink of second bailout for banks**

But why not 😺  Genesis has its meaning!

To follow the Gitter discussion and continue here, I propose to use `total_kernel_offset` of block header, which is 32-bytes zero in Genesis block, to embed a Mimblewimble declaration message.

> **15/Dec/1890 The Right to Privacy**

pure ASCII code for Genesis `total_kernel_offset`.

What say you?

**Comment by KasparEtter** [comment]
Couldn't/shouldn't it be the hash of the most recent Bitcoin block header to prove that there was no premine?

**Comment by sesam** [comment]
@KasparEtter yes as you say, and the last BTC header hash (fetched and compared between 3 web APIs) is getting included: https://github.com/mimblewimble/grin/blob/master/etc/gen_gen/src/bin/gen_gen.rs#L77

**Comment by ignopeverell** [comment]
You can see it here on the Floonet genesis block:

https://github.com/mimblewimble/grin/blob/dbf8e97b3f504bb753c0f48342e6dfc93376d8ea/core/src/genesis.rs#L56

**Comment by KasparEtter** [comment]
Thanks for the quick clarification! I didn't realize that this is already the case. If I understand this issue correctly, it's only about the following then: https://github.com/mimblewimble/grin/blob/dbf8e97b3f504bb753c0f48342e6dfc93376d8ea/core/src/genesis.rs#L71-L73

Am I right in assuming that we can encode a string there without any special treatment by simply using the same offset in the single output below?

In order to honor the inventor, He-Who-Must-Not-Be-Named, I suggest `I call my creation Mimblewimble.`, which is 32 characters long. (The period can be dropped if a null-terminated string is preferred.)

Alternatively `Crypto is our source of magic.`, which is shorter and freely adapted from [this quote](https://www.reddit.com/r/harrypotter/comments/16m75v/words_are_our_most_inexhaustable_source_of_magic/).

**Comment by svechinsky** [comment]
I like the idea of having a news headline from the day of the launch.
I'm sure that the current state of affairs will lead to something interesting being posted that day.

Crypto is our source of magic is also very cool

**Comment by garyyu** [comment]
`Crypto is our source of magic.` can be suitable for any crypto, so it's not very specialized for Mimblewimble / Grin.

**Comment by eupn** [comment]
https://github.com/mimblewimble/docs/wiki/No-this,-no-that

>no genesis message

**Comment by lehnberg** [comment]
Closing on the basis of decision taken in Jan 3 Governance meeting:
https://github.com/mimblewimble/grin-pm/blob/master/notes/20190103-meeting-governance.md#921-genesis-message
