### ISSUE TITLE
Lookup list of seed servers from a DNS record

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#218]
For now we simply download a file on github that has a list of server names. This was the simplest to get started but we need something less dependent on github. Add the ability to list all A records from a DNS name to feed seed connections.

**Comment by sesam** [comment]
Testnet uses WebStatic = http://grin-tech.org/seeds.txt which is no more or less secure than DNS. If grin-tech.org gets a reddit hug this might fail.

We have /v1/peers/all which is perhaps too chatty.

Suggestion:
1. add /v1/peers/listening (listing only API roots of "full" nodes)
2. change WebStatic to a list of long running API roots of whoever is communicates with the project, stays upgraded, and agrees to be listed, so we remove one level of indirection. Anyone who wants can then list both HTTPS and HTTP. Fast start could pick a single HTTP peer to know block height (with low peer timeout, maybe even lower than current "< 5s"), then prioritize getting HTTPS peers.

## If we really need DNS
HTTPS works where DNS won't. On the other hand, there are Hotspot wifi points that might let through some DNS or other low level traffic unharmed, if we want to get crafty later on to escape any naive attempts at forcing a chain split.

This use case is often solved with TXT records. If we add a dependency on the [trust_dns crate](http://trust-dns.org/target/doc/trust_dns/rr/rdata/txt/struct.TXT.html) we'd get TXT records.

Using A would require as many DNS requests as there are lines in the seed list, though if a single seed is enough then round-robin could be a nice side-effect. On the other hand, 1 of 3 of the grin projects current seeds was offline yesterday, and making a single DNS request is better than 3.

CNAME could be abused to ascii armor a short list of (IPv4, port) tuples, but that's hard to decode and not human readable.

## Privacy issues
Then there's the issue of privacy; any client requesting the seed list tags themselves as a grin user. Before that becomes a concern, maybe grin can tag on to some less trackable discovery methods, i.e. use some existing E2E chat solutions to get a better anonymity set and plausible den. of having crypto.

Possibly tagging on to some file that M2M communications keep hitting. /favicon.ico probably not; but robots.txt / humans.txt / abuse.txt allows for free form comments.

**Comment by sesam** [comment]
Also, we'd like to be able to filter the list of full peers by genesis block hash, so a Testnet1 peer only gets Testnet1 blocks. This might again cause privacy issues, making it easier to locate grin developers.

**Comment by ignopeverell** [comment]
There seems to be some confusion between discovery of the *first* peers and discovery of the network. Seeds are just the former. You start your node, it needs at least one IP address to connect to. From there, the regular gossip at the protocol layer allows discovery of more peers (there's a `get_peer` message).

Using a node endpoint like `/v1/peers/all` doesn't help, because you still need to know a node. So how do you get the first IP? Name resolution is kinda what DNS is for. We don't really need to reinvent the wheel, that's how every cryptocurrency I know enough about works.

You can have multiple A records on a single domain. So the idea is to have a handful of domains, each with multiple A records that point to stable sets of peers. The people who publish that DNS record have to be somewhat public, that's the only issue, because of DNS registration. In most projects though, a few people at least can do that.

Fun fact is early version of bitcoin (I think it got removed in 0.8) had the option to seed over IRC (like your chat solution). It proved somewhat brittle and overly complicated I think.

**Comment by sesam** [comment]
OK, DNS gives speed and DoS of the first-ever bootstrap, and if people bring their .grin folder along as they go that'll be enough.

Any old dyn-dns provider can be used, and we eliminate the WebStatic option.

Is the steps:
1. DNS A-record lookup (5-120ms latency)
2. immediate tokio_io connection to recieved over IPv4 or IPv6 and default port?

In seeds.txt, only li149-16.members.linode.com seems to be have reverse-DNS. If we add a bunch of domains, like some CloudFlare free tier, some dyndns, some paid with high capacity, that should be redundant enough. Any ideas who wants to put their name in the DNS registry? Some supportive businesses?


Longer term, maybe allow users to paste in a HTTPS api endpoint somewhere. Could enable all kinds of proxying and always using a trusted friend's node, etc. Shouldn't be a big cost, since hyperion likely can't be eliminated even in a stripped down "border node" behind which other nodes can hide, to protect miners etc from breakins. A crazy URL could even support port knocking: https://x.com:21:22:21:13144
Before, and if DNS attempts fail, it might be good to try localhost. Shrewd users can port-forward, even
ssh -L 13144:ginny.io:13144, if there's firewalling of all except 80,443, and outgoing SSH as public wifi often is. More exotic options: UDP-over-DNS (bad bandwidth/latency) or steganography for both  for control and data signaling via apparent spam messages over abandoned wikis or weird image boards.
