### ISSUE TITLE
Chain won't sync stays forever at step 2/4

### ISSUE THREAD

**Issue by ocminer** [mimblewimble/grin#2291]
Downloaded the latest binary on a linux testbox, forwarded ports but the sync stops at step 2/4 and stalls there forever.

**Comment by vitalisator** [comment]
same problem here.

**Comment by garyyu** [comment]
that's a known issue and already fixed in https://github.com/mimblewimble/grin/pull/2289, please build from the latest master branch.   And restart grin when you stuck on this, in case you’re waiting a peer which’s not updated.

I close this for the moment, and if still problem, please re-open it.

The binary released is not updated yet and should be made soon.
