### ISSUE TITLE
Garbled screen/TUI

### ISSUE THREAD

**Issue by jogc** [mimblewimble/grin#2429]
https://prnt.sc/m9b2th
Is is really supposed to look like this?

Grin: grin-v1.0.0-479973573-linux-amd64.tgz
OS: Debian GNU/Linux 9 (stretch)

I'm viewing it over SSH from a Terminal window in MacOS

**Comment by hashmap** [comment]
If you don’t like it check output of `locale‘ command and make sure that LC_LANG, LC_LANGUAGE and LC_ALL are not empty and set correctly.

**Comment by mmazi** [comment]
I'm using the Terminal Mac application. The problem was resolved by checking the checkbox "Set locale environment variables at startup" in Preferences - Profiles - advanced:

<img width="359" alt="Screenshot 2020-01-29 at 09 34 51" src="https://user-images.githubusercontent.com/294075/73340299-c4989a00-427a-11ea-9eb6-4cbf6f22622e.png">
