### ISSUE TITLE
Merge mistake

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#2769]
Gary Yu @garyyu 10:39
Problem found, it’s in #2720, which merged master to 1.1.0 branch but overwritten some merged PR in 1.1.0, including #2575, don’t know what else had been overwritten.

The possible lost merged PRs:
<img width="1260" alt="Screen Shot 2019-04-21 at 10 54 21 AM" src="https://user-images.githubusercontent.com/1852227/56464814-e9c2c700-6423-11e9-9728-4623f177e27c.png">

All above PRs need to be checked (both in 1.1.0 branch and latest master branch), or find a base in 1.1.0 branch before #2720 to merge again.

**Comment by yeastplume** [comment]
It’s possible one or two of these things were merged incorrectly, which is why I asked all developers to check their PRs in the merge PR here https://github.com/mimblewimble/grin/pull/2756. 

As for a the list of ‘lost’ PRs, there were 3 fairly messy merges done over 3 months that I believe were mostly okay (I can tell just by scanning through that list and my 1.1.0 testing that most of those were merged correctly), however there’s every chance on or two things were missed, which is why we’re letting the new master sit for a bit before releasing to shake out these issues. By all means everyone should be sanity checking their bits of functionality are working correctly in 1.1.0. but it’s not the case that dozens and dozens of PRs were lost in the current master.

**Comment by kargakis** [comment]
https://github.com/mimblewimble/grin/pull/2753 seems to be missing too

**Comment by kargakis** [comment]
This issue can be closed now
