### ISSUE TITLE
Error sync at height 105

### ISSUE THREAD

**Issue by BloddyBaron** [mimblewimble/grin#279]
The error in sync started at height 105. Deleting .grin in server folder solved it, but still no idea why it failed to sync. 
[grinlog.tar.gz](https://github.com/mimblewimble/grin/files/1480240/grinlog.tar.gz)

**Comment by ignopeverell** [comment]
Looking at the logs, there was a fork at height 102 and your node only saw the losing side. For some reason (relay related most likely, you had only 2 peers at the time), you never got the winning 102 block (d8c1f7c5). Then you restarted but didn't leave it on for long enough for sync to catch on (it would have needed at least 10 seconds).

This would be fixed by #226 so I'll close. Thanks a lot for the log file, it helped narrow down this failure scenario!
