### ISSUE TITLE
The link to "transaction UML" in the docs' TOC is broken

### ISSUE THREAD

**Issue by fresheneesz** [mimblewimble/grin#2792]
**Describe the bug**
In the [table of contents](https://github.com/mimblewimble/grin/blob/master/doc/table_of_contents_.md), the link to "transaction UML" is broken. I also don't see anywhere that clearly explains the protocol for a mimblewimble transaction (specifically what steps there are in the back-and-forth, and what data is sent in those steps). I assumed that's what the link to "transaction UML" was for.

**Comment by lehnberg** [comment]
Thank you for raising an issue about this! This is probably due to a move of wallet into it's own repo, `/grin-wallet`. The correct link to the transaction UML is here: https://github.com/mimblewimble/grin-wallet/blob/master/doc/transaction/basic-transaction-wf.png

Would you mind raising a PR to fix this?

**Comment by fresheneesz** [comment]
Alright, created a PR: https://github.com/mimblewimble/grin/pull/2798

**Comment by lehnberg** [comment]
Awesome - looks it's merged already! Closing this one now, thanks for your help @fresheneesz!
