### ISSUE TITLE
GetPeerAddrs Enhancement

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#2883]
Today I want to get a view about how many Grin nodes are running with each version and how many Grin nodes alive totally.

But unfortunately, currently there's no good way to do that, we only can get very draft view for example as https://grin.report/d/jeTROiqmz/peers?orgId=1.  It's a statistics by the `connected peers` with this API:
```
$ curl -0 -XGET http://127.0.0.1:3413/v1/peers/connected 2>/dev/null | jq
```

But with above API, we only have a small view from one node and the denominator is too small (for example, 259 connected peers in above `grin.report` at this time).

Or we can use `/v1/peers/all` API to query all peers in local node peers database:
```
$ curl -0 -XGET http://127.0.0.1:3413/v1/peers/all 2>/dev/null | grep  user_agent | grep -v '""'
```

With above API, the denominator could reach `673` for example in one of my nodes.

But anyway, there're 2 problems here for getting an accurate statistics:
1. There's no unique ID for node, we can't ensure a recorded peer info is a unique node. For example, a Grin node running under a VPN (or i2pd in the future) will be recorded as multiple peers because the public IP will change from time to time.

2. Most of the nodes are in the `outbound only` network environment, they can't accept incoming connection. So, a view on ONE node is very small since we can't expect all Grin nodes in the network has tried to connect this ONE node.

For problem 1, perhaps we can enhance the Grin p2p protocol to have sth like `gnode://pubkey@ip:port` as the Grin node ID, we can add `pubkey` in the `Hand/Shake`.

For problem 2, perhaps we can enhance the p2p protocol to have a new version of `Type::PeerAddrs` which currently is just pure ip address list. Then we can have a clear view about all nodes from one node thanks for `GetPeerAddrs`.

For example we can enhance it as:
```
pub struct PeerAddrs {
	pub peers: Vec<NodeInfo>,
}

pub struct NodeInfo {
	pub node_id: String,    //  node pubkey
	pub addr: SocketAddr,    // this is the only info currently provided
	pub height: u64,
	pub user_agent: String,
	pub last_seen: DateTime<Utc>,
}
```

***Updated @ 11th June***
The node ID is definitely a bad idea considering the privacy concern.
I change this issue title to `GetPeerAddrs` enhancement to reuse this issue for further discussion on this improvement topic.

**Comment by lehnberg** [comment]
I would have thought the lack of unique identifiers in a privacy focused P2P network to be a feature and not a bug. Is there a use case for this beyond obtaining more accurate statistics?

**Comment by chisa0a** [comment]
> perhaps we can enhance the Grin p2p protocol to have sth like gnode://pubkey@ip:port as the Grin node ID, we can add pubkey in the Hand/Shake

I like the idea of measuring Grin network health @garyyu. Maybe to enhance user privacy, we can also use a level of indirection where the `pubkey` is hashed together with a salt, and churned on a regular basis. This would further obfuscate which node belongs to which user, and wouldn't affect number of total nodes / versioned nodes.

Also, not sure what you mean by `pubkey` since the public keys in Grin are unique per-transaction. Either way, would advocate toward using ephemeral data if it will be broadcast on the net.

> perhaps we can enhance the p2p protocol to have a new version of Type::PeerAddrs which currently is just pure ip address list.

In @ignopeverell's and my I2P work for Grin, we are using an [enum for `PeerAddrs`](https://github.com/ignopeverell/grin/pull/2/files#diff-d0a0e5205febb43dc810bf0cc19377b0). Imagine it would be fairly easy to wrap this into the `addr` field of your `NodeInfo` struct, but imho this would be nightmarish to serialize/deserialize from the config ([see these examples](https://github.com/ignopeverell/grin/pull/2/files#diff-229b829b1539581fe473cd72bb30884e) for how it's already starting to blow up).

As somewhat of an aside, how useful are unique identifiers and meta information to network health? Publicly broadcasting static identifiers and other meta information seem to open a fairly large fingerprinting attack surface. Imho, these stats should be opt-in by default, and/or removed as much as possible.

**Comment by kargakis** [comment]
I am going to echo @lehnberg, I think uniquely identifying nodes in the Grin network would go against the very main goal of Grin that is privacy.

**Comment by chisa0a** [comment]
While re-reading the Dandelion++ paper, came across this quote:

> If the user is using the same pseudonym for different transactions, this linkage is trivial. However, even when users use fresh keys for different transactions, practical attacks have been able to link the pseudonyms

While I assume you are well-intentioned @garyyu, your scheme seems hugely detrimental to Grin privacy.

**Comment by garyyu** [comment]
Ah! all of you are very right 👍   Adding such kind of node ID is definitely a bad idea for the privacy concern,  sorry for it and please forget this ID thing.

And I still want to propose to enhance `GetPeerAddrs` for better info of network healthy, we just need here then: 
```
pub struct PeerAddrs {
	pub peers: Vec<NodeInfo>,
}

pub struct NodeInfo {
	pub addr: SocketAddr,    // this is the only info currently provided
	pub height: u64,
	pub user_agent: String,
	pub last_seen: DateTime<Utc>,
}
```

(will change the issue title to reuse it for this discussion)

**Comment by yeastplume** [comment]
Going to close as this hasn't been followed up on, feel free to re-open or follow up in the node dev group
