### ISSUE TITLE
server doesn't sync from genesis block onwards

### ISSUE THREAD

**Issue by photis** [mimblewimble/grin#304]
I noticed my mining server was out of sync with the network. This has happened a few times in the past 24 hours and is a known issue. My usual approach is to: 
- stop the mining server, 
- delete the .grin folder and 
- restart the server in validation mode only, let it sync the whole chain, 
- stop it again and 
- restart with mining enabled. 

I kept the wallet.dat file as is. Left the wallet listener running as well.

The server didn't start syncing from the genesis block onwards but continued with the head of the chain, then at height 2377. No new .grin directory was created.

Log file at https://gist.github.com/photis/f8cbfd3de4dcd6e80e4fbfdccf73ab3e

**Comment by ignopeverell** [comment]
Your server was still at genesis and block 2377 was refused as orphaned as would be expected. What happened is after your restart, the server wasn't able to start syncing. And despite having a lot of peers it looks like you were only connected to 2, which would explain the difficulty in sync. This was very likely fixed by #296 and #300. Please try again on the latest update and feel free to reopen if you see this again.
