### ISSUE TITLE
default log levels in config file (revert breaking change)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#3117]
We tweaked log level config here - https://github.com/mimblewimble/grin/pull/3064

It used to be `Info` but now we also support `INFO`.

But - we now generate config file with default entries like - 

```
#log level for file: Error, Warning, Info, Debug, Trace
file_log_level = "INFO"
```

These actually introduce a breaking change with previous code which does not support them 
 where `Info` is supported, not `INFO`.

We should revert the config file generation to add default log level consistent with previous behavior (and also consistent with config file comments).

```
#log level for file: Error, Warning, Info, Debug, Trace
file_log_level = "Info"
```

**Comment by antiochp** [comment]
For context this is what we see with previous code and new default config file -

```
thread 'main' panicked at 'Error loading server configuration: 
Error parsing configuration file at /antiochp/grin/node_mainnet/grin-server.toml - 
unknown variant `INFO`, 
expected one of `Error`, `Warning`, `Info`, `Debug`, `Trace` 
for key `logging.stdout_log_level`', src/bin/grin.rs:124:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by JosephGoulden** [comment]
It's a bit awkward because now we are using the log levels from the log crate, which when serialised are upper case. And the config file is generated by just serialising the config struct that has LogLevels as fields.

Couple of options, neither of which I particularly like.
1. Apply some post config generation step to get the log levels into the correct (e.g. Info) format.
2. Change the type from LogLevel to String on the LoggingConfig. This would work okay but we lose type safety.

Can we definitely not allow the change? Given that it only breaks if you used new code to generate the config file then reverted to a previous code version.

**Comment by antiochp** [comment]
Either 1 or 2 would work fine here I think. It makes sense _why_ this happened but we should avoid introducing breaking changes like this for little or no benefit.

Maybe the default value for these logging config entries simply post-process to get the capitalization to follow the existing format.
