### ISSUE TITLE
Decoy outputs

### ISSUE THREAD

**Issue by eupn** [mimblewimble/grin#3126]
Beam have decoy outputs implemented, but I haven't deeply investigated how it's done and whether it's a viable idea or not at all. Do we want the same feature? At the first glance it's not something that will fundamentally change the protocol and require hard-fork, but please correct me if I'm wrong.

If we don't have that implemented, but the idea turns out to be viable, I would like to take a stab on it. Though I'd like to have a slight mentorship from the people who know blockchain-related codebase well (@antiochp, probably).

**Comment by tendersoft-mjb** [comment]
According to this paper: https://github.com/bogatyy/grin-linkability current Grin implementation is flawed and allows for near 100% transaction linkability. The author points out that decoy outputs would most likely not solve this issue effectively.

**Comment by eupn** [comment]
We're steel need to consider the ways to increase anonymity set, this is one of them. Even if it's not obscures TX graph entirely, it indeed helps with plausible deniability for individual TXOs.

**Comment by tendersoft-mjb** [comment]
From what I have read it does not increase the anonymity set at all, since all decoy outputs could be filtered rather easily.

Besides, obscuring TX graph i.e. who paid who, is way more important than hiding the amounts, so it seems Grin design got it backwards, because it exposes TX graph and hides the amounts.

Tinkering around the edges with decoy outputs does nothing to address the larger issue of broken design.

**Comment by lehnberg** [comment]
Thanks for your input @tendersoft-mjb! 

> Besides, obscuring TX graph i.e. who paid who, is way more important than hiding the amounts, so it seems Grin design got it backwards, because it exposes TX graph and hides the amounts.

This statement doesn't quite make sense to me. If you do not obscure commitment amounts, how would you be able to hide the TX graph? It would be straight forward to link commitments that appear in a certain time window even if commitment `X` would not spend to commitment `Y` directly. What am I missing here?

**Comment by tendersoft-mjb** [comment]
True, some amount bundling/hiding is necessary as they too leak TX graph information.

Still, TX graph should be hidden completely otherwise there's actually no real benefit in using Grin compared to already existing crypto.

**Comment by pstavraetos** [comment]
> Still, TX graph should be hidden completely otherwise there's actually no real benefit in using Grin compared to already existing crypto.

Without to redesign current MW-protocol in some new protocol it is impossible to hide entire tx-graph since every new node connecting to network needs to check blockchain consistency and since thereis input/output model of blockchain as a consequence tx-graph will exist.

If you discard input/output model then, yes, you will have no tx-blockchain but only accounts-state-blockchain but consensus will be broken for any new node connecting to network - it will need to trust for the current acoounts value which is something Satoshi avoided from the initial blockchain design.

**Comment by eupn** [comment]
@pstavraetos actually, during IBD there are already blocks that have transactions in them cut-through and thus pruned with linkage data being lost.

**Comment by pstavraetos** [comment]
> @pstavraetos actually, during IBD there are already blocks that have transactions in them cut-through and thus pruned with linkage data being lost.

Yes, but such trick is not comparable with full discard of input/output model where any time moment you have only current balances of users and nothing more.
