### ISSUE TITLE
ERROR grin_p2p: protocol - handle_payload: BanReason BanReason { ban

### ISSUE THREAD

**Issue by TheBudda** [mimblewimble/grin#3177]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Run 'Grin Version 3.0.0-beta.3 (proto: 2)' & wait
![Grin_Screenshot](https://user-images.githubusercontent.com/16983376/71514010-be3a8b00-2894-11ea-90b7-518452f15e06.png)
![Grin_Screenshot1](https://user-images.githubusercontent.com/16983376/71514016-c1ce1200-2894-11ea-8bcb-693b23f41ff1.png)

2. Expect 'no errors'
3. Scroll down to 'Logs'
4. See error:
ERROR grin_p2p: protocol - handle_payload: BanReason BanReason { ban_reason: FraudHeight }

**Relevant Information**
my log in grin ui: ERROR grin_p2p: protocol - handle_payload: BanReason BanReason { ban_reason: FraudHeight }

**Screenshots**
Please see attached screenshots

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Version: 18.04.3

**Additional context**
This is on a dedicated server from OVH

**Comment by antiochp** [comment]
It looks from the 2nd screenshot that you sync'd successfully and that you are not getting banned by everyone (or banning everyone else).
So I think this is probably expected behaviour. During sync your node is busy syncing and maybe not as responsive as it would normally be. Another peer has requested header from you and you did not respond in a timely fashion and you were subsequently (and temporarily) banned.
This will resolve itself over time as you will be unbanned by that peer in a few hours.

**Comment by antiochp** [comment]
I do think we are going to want to revisit this behavior at some point though - we are arguably overly aggressive here in terms of banning peers unnecessarily.
