### ISSUE TITLE
url length limit when refreshing wallet outputs (many query params)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#321]
```
GET /v1/chain/utxos?id=xxx&id=yyy&id=zzz
```

Not sure what the limit is here but we are going to hit it at some point now that we have a large chain on testnet.
Wallet should probably split this up into multiple smaller api calls.

**Comment by rloomba** [comment]
I'm new the codebase and hoping to contribute.

I'm seeing that `refresh_outputs` fn will probably need to updated [here](https://github.com/mimblewimble/grin/blob/master/wallet/src/checker.rs#L55).

Can you point in the direction of what the smaller api calls might look like? split the API calls into smaller batches so that there's only a max of 100/500/1000 ids in a request?

**Comment by antiochp** [comment]
Yeah. Maybe 500 at a time (I don't actually know what the limit should be).
Then batch them up and call the same api call for each batch of ids - 

```
GET /v1/chain/utxos?id=1&id=2&id=3&...
GET /v1/chain/utxos?id=501&id=502&id=503&...
etc.
```

(the ids would not actually look like these as they are commitments but same basic idea)

**Comment by rloomba** [comment]
cool, makes sense. Will give it a shot.
