### ISSUE TITLE
The block was not credited

### ISSUE THREAD

**Issue by githubusrR** [mimblewimble/grin#3257]
Ubuntu 18.04
Grin Version 3.1.0-beta.1 (proto: 2)

log:

20200301 08:50:18.905 WARN grin_servers::mining::stratumserver - (Server ID: 0) Solution Found for block 588628, hash 000047e46564 - Yay!!! Worker ID: 12, blocks found: 1, shares: 759
20200301 08:50:18.905 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 588628, hash 000047e46564, edge_bits 31, nonce 3610856989469486504, job_id 0, difficulty 1433803041/1227045549, submitted by rig3

Everything is fine in the log, but there is no block enrollment, there were no rejects either

On the wallet in balances it is not present and in txs

**Comment by jaspervdm** [comment]
The coinbase reward doesn't show up in your wallet because the block was orphaned: [your block](https://grinscan.net/block/000047e46564d3ba78dd0fa37ee253a79927c8287fe8c653658cc0eaa822ae27) vs [block in longest chain](https://grinscan.net/block/588628)

**Comment by githubusrR** [comment]
What caused this?

**Comment by jaspervdm** [comment]
Short lived forks are normal, especially with 1 minute block times

**Comment by githubusrR** [comment]
how does one choose who gets the block?I understand reorg but here the block was accepted

**Comment by jaspervdm** [comment]
Both you and a competing miner found a block at height 588,628 at roughly the same time and broadcast it to the network. Due to network topology and latency the order in which the blocks are received is not the same for every node. So some of the miners received the other block before they received yours, meaning they build their own block at 588,629 on top of the other one. This caused yours to be orphaned, as now the longest chain doesn't include your block. This is a very normal statistical process that happens in every PoW chain.
