### ISSUE TITLE
Support Apple Silicon

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#3545]
Currently Grin does not build on Apple Silicon (ARM M1). For two reasons:
- Ring must be updated to >="0.16.16". Easy fix with `cargo update -p ring`.
- croaring-rs (in fact croaring-sys does not compile for an unknown reason. See https://github.com/saulius/croaring-rs/issues/66. EDIT: Fixed by https://github.com/saulius/croaring-rs/pull/67. Wondering if we still need that fork of croaring btw.

**Comment by trevyn** [comment]
>Wondering if we still need that fork of croaring btw

Looks like our fork is just to define `DISABLEAVX` in [`build.rs`](https://github.com/mimblewimble/croaring-rs/blob/444e8176d46a8c6f44a15b9e17455714e4b3e42d/croaring-sys/build.rs#L14):

```rust
builder.define("DISABLEAVX", Some("1"));
```

for CRoaring's use in [`portability.h`](https://github.com/RoaringBitmap/CRoaring/blob/052fb54656f77ac843a7540c02a62d3fa4a0e051/include/roaring/portability.h#L68..70):

```c
#if (!defined(USEAVX)) && (!defined(DISABLEAVX)) && (defined(__AVX2__))
#define USEAVX
#endif
```

Since the fork, `croaring-rs` upstream [added](https://github.com/saulius/croaring-rs/pull/62) and published a feature to set the `-march` LLVM flag:

>You can specify `ROARING_ARCH` environment variable to control the target CPU architecture, e.g. `ROARING_ARCH=ivybridge cargo build --release`

which of course should appropriately toggle the `__AVX2__` definition and have the same effect.

(List of valid architectures in [llvm/`X86TargetParser.cpp`](https://github.com/llvm/llvm-project/blob/4a17ac0387f078529da02e355a24df99f645d364/llvm/lib/Support/X86TargetParser.cpp#L291..L412))

Since this moves the setting from a crate feature to an environment variable, how do we want to handle this? Provide instructions to the user to compile their own binaries with this setting if necessary, or include a baseline arch in the [`ci/release.yml`](https://github.com/mimblewimble/grin/blob/master/.ci/release.yml), maybe `core2` or `nehalem`?

Either way, happy to do a PR to remove our `croaring-rs` fork, switch to upstream, and add the supporting bits.

possible xref: https://github.com/mimblewimble/grin-wallet/issues/479

**Comment by quentinlesceller** [comment]
Interesting @trevyn. I'd vote for using the original repository of croaring and have a release without AVX enabled. Why `core2` and `nehalem` specifically?

**Comment by trevyn** [comment]
`core2` and `nehalem` seem like reasonable microarchitectural cutoffs without being too ancient. For reference, Nehalem is where you get SSE 4.2, and Haswell is the start of AVX2. I suppose it mostly depends on how far back we want to target.

In the meantime, I'll prep a PR using the original repository of croaring.

https://en.wikipedia.org/wiki/List_of_Intel_CPU_microarchitectures#x86_microarchitectures: ("Core" here is `core2` in LLVM-speak, I believe)
<img src="https://user-images.githubusercontent.com/230691/111326706-381b8780-8686-11eb-8e3e-ef488985c7aa.png" width=170>
<img src="https://user-images.githubusercontent.com/230691/111327078-829d0400-8686-11eb-8b95-1045ec1e6a11.png" width=400>

**Comment by trevyn** [comment]
Ah, there's a specific bit about this in [`portability.h`](https://github.com/RoaringBitmap/CRoaring/blob/63a54b15df3bc8fad77a9cc26fbc2dcce5f8da23/include/roaring/portability.h#L50..L65):

```c
///////////////////////
/// We support X64 hardware in the following manner:
///
/// if IS_X64 is defined then we have at least SSE and SSE2
/// (All Intel processors sold in the recent past have at least SSE and SSE2 support,
/// going back to the Pentium 4.)
///
/// if USESSE4 is defined then we assume at least SSE4.2, SSE4.1,
///                   SSSE3, SSE3... + IS_X64
/// if USEAVX is defined, then we assume AVX2, AVX + USESSE4
///
/// So if you have hardware that supports AVX but not AVX2, then "USEAVX"
/// won't be enabled.
/// If you have hardware that supports SSE4.1, but not SSE4.2, then USESSE4
/// won't be defined.
//////////////////////
```

Based on this, I think `nehalem` would be a good choice for an equivalent to `DISABLEAVX`, as long as 2008 is an acceptable cutoff year. It seems that CRoaring does not have a switch for "AVX but not AVX2".

**Comment by trevyn** [comment]
```
% rustup show
Default host: aarch64-apple-darwin
rustup home:  /Users/m1/.rustup

stable-aarch64-apple-darwin (default)
rustc 1.50.0 (cb75ad5db 2021-02-10)
```

```
git clone -b trevyn-croaring-defork https://github.com/trevyn/grin.git
cd grin
cargo update -p ring
cargo build
cargo build --release
cargo test --all
```

All work 100%. That thing is *fast*.

**Comment by quentinlesceller** [comment]
We now support Apple Silicon! Thanks @trevyn
