### ISSUE TITLE
Move repository out of mimblewimble group

### ISSUE THREAD

**Issue by maaku** [mimblewimble/grin#358]
Mimblewimble is the name of a idea for extending confidential transactions to support OWAS, cut-through, and compact chain sync natively. It is not a specific implementation, nor is the coiner of the term mimblewimble associated with the grin project as far as we know. It is disengenous and confusing for grin to co-opt the "mimblewimble" name as referring exclusively to itself. Please consider switching to an alternative group name (grin/grin is unfortunately taken, but I'm sure an alternative can be found).

**Comment by LordMajestros** [comment]
I honestly don't see the problem here. Is someone trying to use mimblewimble for another project? Grin clearly states 
```
Minimal implementation of the MimbleWimble protocol. 
```

**Comment by sesam** [comment]
Also note that the "mimblewimble" github user/project has *promised to keep open access to other implementations to join under the /mimblewimble github account. So they pay the bills for github, basically. And the community get to add stuff, and if there's scammy behaviour, the community gets to throw these projects out of /mimblewimble. Better than having projects spread out all over the internet, with no way to tie them together.
(. The other option would be a PoW blockchain for tracking the trustability of various MW implementations .)

**Comment by yeastplume** [comment]
@maaku I can see your point, and agree with the distinction between the technology and the implementation. However there are already several mimblewimble.* domain names that have been snapped up by unknown persons, and at least one attempt by an "Ethereum Token ICO" project to unashamedly call itself 'mimblewimble'. We don't claim any divine right to be the guardians of the name, but if this project and the people involved don't at least make an attempt at it, plenty of other unsavoury parties will absolutely and unreservedly take the name for themselves.

There is nothing disingenuous about any aspect of this project or any of the main people involved, nor does grin make any claim in any place that it *is* mimblewimble. Plenty of other projects won't be making the same effort to keep that distinction. In the absence of the originator of the term becoming known, and since many people involved with the project are very closely linked to the origins of the technology, I don't see a problem with this project owning the github name 'mimblewimble' so long as it keeps its pledge to share it with other genuine mimblewimble-based projects.

**Comment by yeastplume** [comment]
Going to close this for now. @maaku if you want to continue this discussion, the mailing list is probably a better bet. Only a small subset of the community watches github issues, and you're likely to get more opinions there: https://launchpad.net/~mimblewimble
