### ISSUE TITLE
Support for Aggregate (Schnorr) Signatures

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#399]
Likely a meta-issue as this includes multiple moving parts:

* Merge the secp256k1 PRs for aggsig support (461 and 473 I believe) in our fork.
* Integrate it into our fork of Rust secp.
* Implement a building library for aggsig transactions.
* Integrate in the wallet.

**Comment by yeastplume** [comment]
Just leaving these here, as I think these are the most up-to-date descriptions of how a Schnorr enabled transaction should work:

https://lists.launchpad.net/mimblewimble/msg00087.html

https://lists.launchpad.net/mimblewimble/msg00091.html

**Comment by yeastplume** [comment]
Quite happy to take this on when the time is right.. but what's the status of the PR itself? 473 was closed in favour of 486, but It 473 currently looks like it needs a rebase. Think this is a couple of months off, anyhow.

**Comment by ignopeverell** [comment]
It might need a little cleanup, may be good to check with @apoelstra.

**Comment by apoelstra** [comment]
461 needs to be rebased on 486 and it still hasn't seen serious review, only performance review. There is also no good API for single-signer signatures, which is what grin needs. Please do not merge these PRs.

**Comment by ignopeverell** [comment]
@apoelstra my concern with that is mostly additional delays when we could parallelize. Building up all the transaction building logic and interaction between wallet is going to take some time. So we're not talking about having any live code using for at least 3 months. And if the APIs secp APIs change, it will likely be a tiny adjustment on our side.

Does that make more sense in that context?

**Comment by apoelstra** [comment]
Yes, ok, that's reasonable enough. Can you [mark the aggsig functions deprecated](https://github.com/rust-lang/rfcs/blob/master/text/1270-deprecation.md) (or some other more appropriate marking, deprecated is just the one that I know how to use) warning that the API is likely to change and that the crypto is not yet reviewed upstream?

**Comment by yeastplume** [comment]
As a start, performed a merge of 468 and 486 into our local branch, described here: https://github.com/mimblewimble/secp256k1-zkp/issues/9. Will move on to trying to get a rust wrapper around them and see how we get on.

**Comment by yeastplume** [comment]
All good so far for the rust wrapper, have it up and working here with a sample test 5/5 sig:

https://github.com/mimblewimble/rust-secp256k1-zkp/blob/master/src/aggsig.rs

the scratch space struct is exposed and part of the aggsig verify api, but in order to make that callable from rust without having to create a whole load more imports (including exposing error callbacks,) i just included a wrapper around aggsig_verify that creates the scratch space on the C side then destroys it after the verification.

**Comment by tromp** [comment]
When would one need to use the function secp256k1_aggsig_verify() ?
I thought an aggsig is used only during construction and then appears on the blockchain as a regular Schnorr sig,
to be verified as such?

**Comment by apoelstra** [comment]
There is no such thing as a "regular Schnorr sig", only single-key aggsigs.

**Comment by tromp** [comment]
ok, so aggsig just denotes a Schnorr signature, either single or multi-key.

**Comment by yeastplume** [comment]
I've added a first pass at some single-signer function (i.e. Single-key Schnorr) here:

https://github.com/mimblewimble/secp256k1-zkp/blob/master/include/secp256k1_aggsig.h
https://github.com/mimblewimble/secp256k1-zkp/blob/master/src/modules/aggsig/main_impl.h

Looking over @tromp's scheme above, it looks like I'll need to add functionality to add nonces separately and provide the sum to the sign function rather than generating them internally (will look at the scheme in more detail now), but what's there is a good starting point, I think.

**Comment by yeastplume** [comment]
So this is a first pass at what this would look like in Grin. Note that I'll need to slice up/expose some of the internal functions in the current single-signer Schnorr implementation in order to support this workflow:

-Sender selects inputs as before
-Sender picks random blinding factors for all outputs it participates in, computes total blinding excess xS
-Sender picks random nonce kS
-Sender posts inputs, outputs, Message M=fee xS*G and kS*G to Receiver

-Receiver receives inputs, outputs xS*G and kS*G
-Receiver picks random blinding factors for all outputs being received, computes total blinding excess xR
-Receiver picks random nonce kR
-Receiver computes Schnorr challenge e = H(M | kR*G + kS*G)
-Receiver computes their part of signature, sR = kR + e * xR
-Receiver responds with blinding excess xR*G, public nonce kR*G, signature sR

-Sender receives xR*G, kR*G, sR
-Sender computes Schnorr challenge e = H(M | kR*G + kS*G)
-Sender verifies receivers sig, by verifying that kR*G + e*xR*G = sR*G·
-Sender computes their part of signature, sS = kS + e * xS
-Sender posts sS to receiver

-Receiver receives sS
-Receiver verifies sender's sig, by verifying that kS*G + e*xS*G = sS*G·
-Receiver calculates final sig as s=(sS+sR, kS*G+kR*G)
-Receiver puts into TX kernel:
* Signature S
* pubkey xR*G+xS*G
* fee (= M)
-Receiver sends completed TX to mempool. responds OK to sender

Witnesses just need to validate S with kernel data, as before (expansion from mailing list pasted below):

(Sum s_j) * G =

/* expand s_j */
Sum (k_j * G + e * x_j) * G =

/* expand x_j */
(Sum k_j * G ) + e * (Sum_j (Sum_i r_i_j - Sum_i q_i_j)) * G =

/* change summation order */
(Sum k_j * G ) + e * ((Sum_i Sum_j r_i_j - Sum_i Sum_j q_i_j)) * G =

/* definition of r_i, q_i */
(Sum k_j * G ) + e * ((Sum_i r_i - Sum_i q_i)) * G =

/* adding in 0 = Sum w_i - Sum v_i */
(Sum k_j * G ) + e * ((Sum_i O_i - Sum_i I_i)) * G.

**Comment by tromp** [comment]
> So this is a first pass at what this would look like in Grin.
> ...
> -Receiver receives sS
> -Receiver verifies sender's sig, by verifying that kSG + exSG = sSG·
> -Receiver calculates final sig as s=(sS+sR, kSG+kRG)

Normally, the signature is of the form (s,e), since it's easier to
represent scalars
than curve points, and kG can be recovered as sG-exG.

**Comment by yeastplume** [comment]
True.. though in the current implementation R is stored (just the x value), so storing R instead just gives us a path of slightly less resistance with what's there between this detail and the fee/message

```
    /* extract R */
    if (!secp256k1_fe_set_b32(&r_x, sig64 + 32)) {
        return 0;
    }
```

Just an implementation detail, I think

**Comment by apoelstra** [comment]
@tromp `(s, e)` is a form that prevents batch validation. Please don't do this. Just use `(s, R)` and require `R` to have Jacobi symbol 1. This is easy to achieve even in a multisignature, if the Jacobi symbol is wrong after step 1 all parties just negate their nonces.

**Comment by apoelstra** [comment]
@tromp `(s, e)` is a form that prevents batch validation. Please don't do this. Just use `(s, R)` and require `R` to have Jacobi symbol 1. This is easy to achieve even in a multisignature, if the Jacobi symbol is wrong after step 1 all parties just negate their nonces.

**Comment by tromp** [comment]
Thanks for setting me straight, Andrew. I thought perhaps you preferred R
because it saves a few cycles, but allowing batch validation is a much more
compelling reason...

**Comment by yeastplume** [comment]
Just working through a first pass at an implementation here, a couple of things come to mind:

1) I'm assuming we don't want to keep the original transaction workflow (this won't be compatible with existing signatures anyhow, so moot point)

2) This is really more of a 'signature exchange protocol' so 2 round trips (actually 1.5, the last response is just an 'OK') are required between sender and receiver. There's been quite a bit of talk about being able to email, avian carrier, etc, transactions back and forth, which is possible but doesn't seem all that practical. I guess you can send 2 emails/pigeons, but both parties need to keep their secret keys/nonces around for the whole process, which means they both need to be persisted if doing this as an offline process.

I'll keep the transaction stages distinct and identifiable and keep the ability anyhow so this at least remains technically feasible, but I don't see how anything other than communicating with a listener will be really practical.

**Comment by tromp** [comment]
> This is really more of a 'signature exchange protocol' so 2 round trips
> (actually 1.5, the last response is just an 'OK') are required between
> sender and receiver. There's been quite a bit of talk about being able to
> email, avian carrier, etc, transactions back and forth, which is possible
> but doesn't seem all that practical. I guess you can send 2 emails/pigeons,
> but both parties need to keep their secret keys/nonces around for the whole
> process, which means they both need to be persisted if doing this as an
> offline process.

Not necessarily. The wallet interaction can establish some unique but
public interaction id
that gets included in all messages and which each wallet combines with
its master or related key to derive all blinding and nonce keys.

-John

**Comment by yeastplume** [comment]
Quite possibly, yes. In any case, I'll get it working in the online mode first while keeping the phases of the operation distinct so we can explore offline interaction possibilities later.

**Comment by sesam** [comment]
To see if I understand the possible issues, first what scenarions are we
solving for?

1. p2p, anonymity prioritized above convenience
2. vendor: one part (payee) is public, the spender deserves anonymity and
privity
3. interactive establishment of some key, comparable with the
magic-wormhole tool, and that is used to exchange enough key material and
re-contact vectors to last a while

Maybe also 2 should be implemented as a special case of 3, to avoid less
metadata-secretive transactions detracting from the fungibility of the
network as a whole.

Since contracts are expectable, will things like passively receiving
donations be possible that way?

There are also advantages to requiring interactivity, that the chances of
paying to a no longer valid address (or where the adress's owner is no
longer around) could be lower.

**Comment by yeastplume** [comment]
This is in now.. we can open more specific issues for any refinements.
