### ISSUE TITLE
Fix block locator with long forks

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#402]
We generate our local block locator based on our current chain. A peer that tries to share its longer fork will only send 500 block headers at a time. If a fork is longer, once we receive these 500 blocks, the locator we generate will still be the same, leading to an endless loop of useless locator requests.

We need to bridge that gap. The most straightforward way is likely to keep track of the headers we got from a given peer during sync and generate our locator based the latest.

**Comment by antiochp** [comment]
In the process of documenting (or at least thinking through) what happens in this case (#405).
My `simple_sync` attempted to solve for this by updating the `header head`.
Did these changes make it into testnet1 branch? If so then I think we're good (the locator is based on the current chain back from `header head`).

But - I'm unclear what happens if we process a block via the normal broadcast mechanism in this case (I believe this was one of the core issues originally) resulting in the head and header head both being reset to the new processed block (potentially on the original chain).

If we are _not_ updating the `header head` based on headers received - one thought I had was to use an additional `sync head` to track where we had sync'd to.
This would effectively be your "keep track of the headers from a given peer" but only keeping track of the latest one, and only for the current `most_work_peer` that we are syncing from.

**Comment by antiochp** [comment]
Ahh - so it looks like `update_header_head ` only updates `header_head` if total_difficulty makes it the "longest" chain.
So yeah - the `header_head` will continue to point at the "old" chain even though we just received 500 headers that progress a different chain toward the "real" longest chain.

**Comment by ignopeverell** [comment]
The header head only gets updated when a more worked header is accepted. So if you start getting another more worked fork, but the first 500 blocks aren't enough to get you more work (the long fork case), then you're stuck. Your sync'd head may help but there are some details to figure out about its lifecycle (i.e. when does it get created, re-created or destroyed). I have a feeling it might be more complicated than simply tracking the last header we got from a peer during sync, but I may be wrong.

One issue you had with your branch is doing away with "sync mode". This is important to the working of the chain and the maintenance of both the header chain and the block chain.

We have an issue where ideally we would refuse gossip-originated blocks while we're in sync. Practically it's still a corner case, although it'd be good to fix it. So if we accept a new block on our "current" chain while syncing to a new, assumingly more worked one, there are a few cases:

1. Our current head still has more work. We just upped the ante for the fork.
2. The fork header *and* body chains have more work. The new block is just extending what we now consider a less worked fork.
3. The fork header head had more work (but no full block yet). This gets a little hooky. We're going to overwrite the header head that's now on the fork with the new block. But we're highly likely to receive one more header from the fork right after that will get us back. Only if we don't *and* that was the last block on the fork are we in a bit of a mess, so that'd still be good to plug.

**Comment by antiochp** [comment]
Discussed this with @ignopeverell on gitter.
Going to experiment with introducing a `sync_head` as a way to potentially track sync status with minimal additional state.

Every new header we process we will update `sync_head` to point to the latest header.

This will allow the sync process to pick up where it last left off.

And if we switch to another fork during sync (for any reason) then we effectively forget about the previous fork by just tracking the latest header with `sync_head`.

**Comment by yeastplume** [comment]
I think this will work.. this is essentially what we were trying to do with the 'buddy' system earlier, except in this case we just keep a single `sync_head` around (instead of one for each peer) and reset it when we switch peers. This wouldn't have worked earlier, but it I think it should now since we have peer banning in place.

Using this, each longest peer we attach to is basically given the benefit of the doubt until they provide a bad block, at which point they're banned and we should switch to a new peer. 

Not sure what will happen in a situation like we have now where a few peers likely have the same bad block. I think when that happens, they should quickly be eliminated, unless you've rolled back because a peer even longer than that appeared then disappeared, and you switch back to another peer with the original bad chain and try to build it again. So I think this is okay.. it'll be annoying and time consuming, but the situation will eventually rectify itself.

**Comment by antiochp** [comment]
See #410 for proposed `sync_head` impl.

**Comment by antiochp** [comment]
Related - #412 (sync itself working as expected but blocks failing validation after receiving locator based headers).

**Comment by antiochp** [comment]
Fixed in #413 (testnet1) - working on porting this across to master.
