### ISSUE TITLE
Reject gossip/broadcast blocks when in sync mode

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#408]
See #402 for related discussion.

We _possibly_ only want to be processing blocks/headers from _either_ the sync process _or_ regular gossip activity at any one time.

I am unclear on the specifics of exactly what happens during switching from one to the other though - feels like there could potentially be the risk of refusing a gossip block, only to have sync turn itself off and miss that block.

**Comment by sesam** [comment]
I got stuck at 135645922 @ 15032, after removing .grin and restarting. My node banned or marked Defunc all the nodes with version 0.1.20171204 before getting stuck, but I can't find any log lines about when the ban happened, or why. I'm sure I had cleaned up .grin/peers at some point after cargo rebuild with latest testnet1 and restarted, since it was a known non-smooth upgrade. In gitter grin/dev mably also mentioned being stuck at 15032.

**Comment by sesam** [comment]
I'd very much like grin to do less unimportant things during sync. With less in grin.log and faster resync, it becomes easier to spot and fix sync bugs.

grin gossip + bans rely on nodes verifying before forwarding, and punishing unhelpful nodes.

The ping/pong means peers already know who is far behind, and can avoid forwarding full blocks that are far in the future to lagging peers. This also incentivises peers to tell the truth about which height they have.

Title suggestion: During sync, ignore all gossip unless it hints about a better total_difficulty chain.

**Comment by sesam** [comment]
@antiochp Was this originally prompted by a problem with syncing and other things happening concurrently? My sync performance ideas suit better in another issue or PR (hopefully) later on.
And this might be closeable :)

**Comment by yeastplume** [comment]
Addressed a while back
