### ISSUE TITLE
Have a website

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#63]
Hard to find us if you don't know github right now...

**Comment by mrme44** [comment]
I can help out with this. I do web development for my job, and would like to contribute to this project. I'm kind of busy this week, but next week I can spearhead getting a MimbleWimble website setup.

**Comment by ignopeverell** [comment]
That would be great. I believe @fernandolobato had proposed some help too but haven't heard from him since then, so don't let that stop you.

**Comment by macdasi** [comment]
What will website include ?

**Comment by fernandolobato** [comment]
Hi guys,


Sorry I did not get back to you about the site. I have just gathered basic information about mimblewimble around the internet and put it on a HTMLUP 5 template, just for starters. I forked the repo Igno had originally set up for the site. You can take a look at:


https://github.com/fernandolobato/site

[https://avatars0.githubusercontent.com/u/9090932?v=3&s=400]<https://github.com/fernandolobato/site>

fernandolobato/site<https://github.com/fernandolobato/site>
github.com
Website for MimbleWimble and Grin development





I can upload it to my server later today so you guts can see it live.


Best regards,


Fernando Lobato


________________________________
De: Haddar Macdasi <notifications@github.com>
Enviado: jueves, 15 de junio de 2017 06:02 p. m.
Para: ignopeverell/grin
CC: Fernando Lobato; Mention
Asunto: Re: [ignopeverell/grin] Have a website (#63)


What will website include ?

**Comment by ignopeverell** [comment]
For now I would go with something very simple. A few short sentences about MimbleWimble and Grin's value proposition (scaling, privacy, decentralized mining), another bit about where we're at (very early) and pointers to github, gitter and the mailing list for people who'd want to contribute.

**Comment by ignopeverell** [comment]
@fernandolobato the repository has no commits in the last 2 months...

**Comment by fernandolobato** [comment]
Switch branch to the proposal, I submitted a pull request to the original repo.


________________________________
De: Ignotus Peverell <notifications@github.com>
Enviado: jueves, 15 de junio de 2017 06:08 p. m.
Para: ignopeverell/grin
CC: Fernando Lobato; Mention
Asunto: Re: [ignopeverell/grin] Have a website (#63)


@fernandolobato<https://github.com/fernandolobato> the repository has no commits in the last 2 months...

**Comment by fernandolobato** [comment]
I did the last commit last night my bad, I did not upload the index.html file =(, I will upload it tonight.


________________________________
De: Ignotus Peverell <notifications@github.com>
Enviado: jueves, 15 de junio de 2017 06:08 p. m.
Para: ignopeverell/grin
CC: Fernando Lobato; Mention
Asunto: Re: [ignopeverell/grin] Have a website (#63)


@fernandolobato<https://github.com/fernandolobato> the repository has no commits in the last 2 months...

**Comment by ignopeverell** [comment]
Continuing on my content-related comment above, we should have a short and ideally understandable description on how we achieve each (privacy, scalability, mining decentralization) and appropriate links to learn more (mostly https://github.com/ignopeverell/grin/blob/master/doc/intro.md).

**Comment by fernandolobato** [comment]
Uploaded a rough draft, just some thoughts. I cloned it at my server if you want a quick read of the texts to give some feedback. 
[http://aleph.com.mx/site/](http://aleph.com.mx/site/)

**Comment by ignopeverell** [comment]
To summarize my comments on Gitter:

* make the bullet points list a little less of a blob, maybe with more of a tile layout with matching icons
* make github link more prominent, maybe by having all the github/gitter/mailing list links in the community section with respective icons
* rework the decentralize section, looks kinda odd as-is, maybe just merge it with the cuckoo cycle tile from the list

**Comment by ignopeverell** [comment]
@fernandolobato where are we with this? Do you need me for anything?

**Comment by legerde** [comment]
I was just proof reading the website:

WAS:
A new design for a cryptocurrency with new blockchain characteristics *to
inhibit *anonimity by completely ofuscating transactions.
SHOULD BE:
A new design for a cryptocurrency with new blockchain characteristics *enabling
*anonimity by completely ofuscating transactions.

This bullet was included twice:
* Relatively fast block time (a minute or less, possibly decreasing as
networks improve).

**Comment by fernandolobato** [comment]
Hey thanks guys, sorry I am currently out for vacations, am gonna be back Wednesday, I'll push and update server!

**Comment by fernandolobato** [comment]
Hey guys, I got back last night. I have pushed the changes to server. Sorry for the long wait, I will be available in the weeks to come, so feedback is appreciated.

http://aleph.com.mx/site/

**Comment by clarkmoody** [comment]
A couple nits on mobile:
* The first paragraph of text is very narrow
* "loosing" should be "losing"
* The three links in Supporting the Community are a bit off center, could
probably be fixed in the media query

**Comment by yeastplume** [comment]
Just had a few thoughts about this, I'm not sure just slamming up a website without having a wider discussion about what we're trying to convey is the right strategy.

Website design/logos/artwork is easy enough to get produced from a mechanical perspective, I have a very large network of artists and web designers I can draw on from previous endeavours and I'll be happy to throw some resources at that part once the project is far enough along.

But overall, it can be dangerous to throw stuff out there without it being part of a coherent strategy, and in order to have that, you need to have an idea of what your messaging is and what 'narrative' you're trying to convey. I know this sounds a bit airy-fairy for us engineering types, but it's a very real and very important consideration, arguably more important than the technology if we're ever looking for serious adoption one day. For instance, the layout of the site suggested here with scrolling layout-du-jour suggests to me that someone is trying to market a coin at me ICO style. I don't think that's quite what this particular project wants to convey. Also, at the moment I don't think it's even decided on what the actual name of the blockchain, implementation and coin are going to be, so it's really best not to put something up there until those are decided on to avoid confusing people by chopping and changing the name.

I'd suggest closing this issue and opening a wider discussion about 'the narrative' that we want to convey and the impression the project should give to the world, and then from that create a series of tasks that work towards conveying it. Given that the project is still in very early days, the discussions don't have to take place overnight. But it would be good to have an issue where these matters can be discussed and considered before actual work is done towards messaging.

**Comment by fernandolobato** [comment]
I completely agree with you. I have been following the development of mimblewimble and learning rust at the same time and I can see the dedication and the strong ideological roots of this project. I agree a on pager will likely not be able to express this. A more robust website with resources, posting ability and a well thought design is needed. With the dangerous and crazy development of ICOs in the previous month it could be easy to be labeled as one. I'd be happy to join the discussion on building the site, and given the proper ideas I would be happy to put my 2 cents.

**Comment by percytheprefect** [comment]
Strong ACK on @yeastplume 's post. I think we should focus on working code before getting the narrative right. MimbleWimble has enough profile in the wider community to draw in the right people we are looking to contribute, the rest of the stuff is just noise for now.

It seems like launching a testnet, and have it be somewhat stable, would be a good indicator we are ready to start working heavily on narrative. 

I would be willing to contribute some monetary resources for a quality website.

**Comment by ignopeverell** [comment]
Agreed as well. I'll just caveat it with the observation that it's a lifecycle. In the short term, I think we should just target a website for developers and technical early adopters to attract more contributors and get more people to run the testnet.

By the time we're ready for mainnet, then yes, we'll need all @yeastplume mentioned.

**Comment by gazhayes** [comment]
I've been watching this project from afar while learning Rust and haven't sent any PRs yet but throwing my 2 cents in anyway. There's plenty of information available already and the right people will be attracted based on the quality of the code and feasibility of the protocol. I'm not sure what the plan is or what motives are at play, but unless you're planning on some kind of premine it's probably a good idea to just let the code speak and not even bother with a site _even with the launch of mainnet_, any active promotion/marketing at all and you'll just be immediately swamped with pump and dump shitcoin miners instead of people who recognize the significance and want it to succeed in the long term.

**Comment by yeastplume** [comment]
@gazhayes I agree with you there, but much as I'd like to avoid a mass pump and dump gold rush, there's a fine line between 'not advertising' and 'pre-mining'. I wouldn't advocate promotion in the sense of sending around press releases and actively soliciting interviews (certainly not at the moment,) but a clean and well presented site that's more oriented as a resource site might be warranted at this stage.

**Comment by ignopeverell** [comment]
To phrase it slightly differently, the noise level in this space being so high, it actually requires effort not to be caught in it. What we're going after is not aggressive marketing, but just presenting a clear picture of what we are to avoid confusion. While for other open source projects, "let the code speak for itself" could work, it's unfortunately not a luxury. The noise will catch up to us whether we like it or not.

**Comment by percytheprefect** [comment]
With regards to not advertising vs premining: 

I think the best policy is to have all discussions available on public forums -- including when we release the genesis block. This may be a little idealistic, but I think the project already has enough profile that there won't be able to be a very successful premine. By premine in this case I mean the only person mining on the public chain is the founder of the project. 

This also may be a little idealistic to say, but I'm hoping that the pump and dump shitcoin miners are actively monitoring discussions on github/mailing lists about this stuff.

**Comment by JollyMort** [comment]
I'm gonna mine some ASAP =) If you pre-announce the genesis block on bitcointalk [ANN], release node/miner binaries etc. I don't think it counts as pre-mine even if low interest. Definitely looking forward to a test release. For the website, since it's also a privacy-focused project, would it be a good idea to adapt a no-JS approach? (check out getmonero.org it's been redesigned recently with that approach in mind). This design was voted upon, and site design [crowdfunded](https://forum.getmonero.org/9/work-in-progress/87558/getmonero-com-redesign) by the community. Just chipping in with some ideas. Cheers!

**Comment by kurious** [comment]
Plenty of people (both genuine supporters and less benevolent types too, I am sure) are watching developments here.  I am not of the latter camp, but I am sure I am not alone.  It is looking a very interesting project. I am personally just looking for a way to invest, I don't mine.

**Comment by activillain** [comment]
New to github, but have been industry web dev for several years. Happy to help with web dev, css etc.

**Comment by yeastplume** [comment]
From Mailing list, picking this up here:

For website and messaging, can I suggest, (rather than taking design inspiration from a Hercules graphics card,) just going for a fairly clean, lightly moderated (for technical accuracy) wiki for the time being in the style of https://en.bitcoin.it? This way, we defer major design challenges (perhaps reducing design needs to a logo and basic colour scheme for now). This also might provide a bit more flexibility around documentation, as at the moment all changes and updates to docs have to be PRed, which can get a bit cumbersome.

I was looking around a bit at this, and think, given the state of the project, the best approach for this might be something that's easily backed up and restored from git, and can be moved around as needed. To this end, some kind of database-free wiki like https://www.dokuwiki.org/dokuwiki might do the trick. Combined with a hardened ngnix docker image, we'd be able to structure it so there's a git repository that's continually updated with the latest changes, we can always recreate the site and web environment from scratch without much effort, and won't ever be tied to any particular person's hosting account or VM.

**Comment by Tsunekazu** [comment]
Agreed with JollyMort's no-JS proposal and yeastplume's recommendation to stick to bare minimum. Since their website is open source, https://github.com/monero-project/monero-site - it could be used with appropriate modifications?

**Comment by mrme44** [comment]
Just a thought to consider. When it comes time to making the actual website, and not just a wiki page, it would be a good idea that you make the repository for the website private to those who are working on it. That way it makes it a tiny bit more difficult for someone to make a fake version of the website with the intent to scam people.

**Comment by amilr** [comment]
Am new here, but isn't http://grin-tech.org/ the website? Simple and short - seems perfect for this stage of the project's development.

**Comment by ignopeverell** [comment]
Yes it is, at least for now as you point. This issue was more meant to track the final website, once we're ready to release, which hopefully will be a little more user-friendly.

**Comment by bigkevmccarty** [comment]
Just wanna add that I agree with @yeastplume 's comments about website design. I love the current design. Anything flashy and sales-y scream ICO scam, and that is not what we're here for.

**Comment by 0xb100d** [comment]
Seconded that site should remain as simple as possible. I have https://grin.mw now going which has the grin-tech site embedded as well as some other easy access resources included/adjacent. Any/all feedback appreciated.

**Comment by burrrata** [comment]
Not sure if it's better to comment here or on Discourse, but grin.mw is by far the best website address possible. Are there plans to pass it to the Grin Council as the official address or something when the new website is designed and ready?

Speaking of designs, there are multiple designs being proposed on this thread (https://www.grin-forum.org/t/help-me-design-and-add-content-to-our-site/1035/44). Is there a process for picking one?

**Comment by rentenmark** [comment]
grin.mw is looking pretty strange right now with what I think was a redesign of grin-tech site

**Comment by ignopeverell** [comment]
Marking this fixed now. Regarding grin.mw I believe it needs a little love from @0xb100d.
