### ISSUE TITLE
less dynamic peering topology (configuration options)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#659]
#657 actually means a network (specifically a test network on localhost) will be a _lot_ more connected.
And this makes some test scenarios a lot harder to test out - "header first" block propagation for example.

It would be really useful to allow some configuration to force certain network topologies.

Simple example case - 

`A <--> B <--> C` 

Normally A would almost immediately peer with C because B would advertise both as known peers.

Banning gets us part of the way there (but bans are not temporary).

Note: 
I think it is also important we avoid _whitelist/blacklist_ terminology here, regardless of the origins of said terminology ([Code of Conduct](https://github.com/mimblewimble/grin/blob/783e4c250d955d7d65469cf9ed890f5030109a91/CODE_OF_CONDUCT.md)).

i.e. some way of specifying peers we will only ever connect to and/or peers we will never attempt to connect to. And these should hold regardless of the direction of the connection (inbound/outbound).

Then we could configure this is - 
* A only ever connects to B
* C only ever connects to B
And neither would know about each other (B would know about both).
And block propagation would be restricted to -  
`A --> B --> C` etc.

**Comment by sesam** [comment]
I like gray-listing; keeping a peer in uncertainty whether we'll accept or deny access. And hopefully without race conditions (pun intended). But that's hard to use during testing.

I think @quentinlesceller made bans temporary, here https://github.com/mimblewimble/grin/pull/631.
( 🙃 And "banning" might bring baggage too, further back in time).

So could banning be enough? Or do we also need an API endpoint to "push" a node to connect to a specified peer? Maybe "POST /peers/ip:port/connect" ?

**Comment by antiochp** [comment]
I think this would be better configured (at least how I was envisioning this) via `grin.toml`.
For local testing it would be useful to have the topology relatively static and predefined.
I'm not sure allowing it to be reconfigurable via api endpoints would buy us much (particularly on node restart which happens often locally).

Bigger picture - something like this is probably useful for configuring "private" or "internal" parts of the network (internal nodes, trusted gateways etc.)
But not sure we need to tackle these use cases right now.

**Comment by ignopeverell** [comment]
For private networks we already have the static seed list. And and option for blacklisting may be useful.

**Comment by antiochp** [comment]
See #665 for ability to configure "deny" list for a peer.

The static seed list does not actually help in this case.
We can configure A to use B as a seed. But A will then receive all of the known peers of B and may try and connect to any and all of them. I would like to have A configured such that it only ever connects to B and no other peers, even if B knows about other peers.

**Comment by sesam** [comment]
Nice. @antiochp is there something more you expect out of #657 or is it
ripe for closing?

On Jan 30, 2018 15:41, "Antioch Peverell" <notifications@github.com> wrote:

See #665 <https://github.com/mimblewimble/grin/pull/665> for ability to
configure "deny" list for a peer.

The static seed list does not actually help in this case.
We can configure A to use B as a seed. But A will then receive all of the
known peers of B and may try and connect to any and all of them. I would
like to have A configured such that it only ever connects to B and no other
peers, even if B knows about other peers.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/mimblewimble/grin/issues/659#issuecomment-361613363>,
or mute the thread

**Comment by antiochp** [comment]
Closing - #665 is now merged.
