### ISSUE TITLE
tree hashing - hash_with_index for non-leaf nodes of the MMR

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#778]
Currently we include the `pos` when hashing leaf nodes. But we do not use the `pos` for non-leaf nodes.

For leaf nodes we construct the hash via - 
```
let mut current_hash = elmt.hash_with_index(elmt_pos);
```

For the non-leaf nodes we construct the hash via - 
```
current_hash = left_hash + current_hash
```

I _think_ we want to consider including the `pos` when generating the hash for non-leaf nodes as well.

Something roughly like - 
```
current_hash = (left_hash, current_hash).hash_with_index(pos);
```

__But__ - I feel like I don't have a good handle on the implications of not doing this (vs. doing this, vs. doing something else). 

Some links here on prior work on "tree hashing modes" and "standard" ways of doing this -
https://www.grin-forum.org/t/tree-hashing-mode/270

**Comment by ignopeverell** [comment]
I think we want to consider including the pos as well. I think it's not a huge deal because they're already built from hashes that include positions and the parent's position is unique with respect to its children. But adding the position everywhere is more consistent and might provide a couple smidgeons of additional security.
