### ISSUE TITLE
Inconsistencies in block sorting validation

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#908]
Seeing a fair amount of these in the logs:

```
INFO Client 76.8.60.122:13414 corrupted, ban (ConsensusError(SortError)).
INFO Client 46.101.149.191:13414 corrupted, ban (ConsensusError(SortError)).
INFO Client 94.210.127.12:13414 corrupted, ban (ConsensusError(SortError)).
```

**Comment by ignopeverell** [comment]
As an example, this happened on this block:

https://grinexplorer.net/block/0565848eca38497d0bd02890bc7d3571a524cf25b9445f55ec90ac9909807522

```
Mar 28 15:20:14.509 DEBG Requesting block 0565848e from peer 139.59.105.169:13414.
Mar 28 15:20:15.104 INFO Client 139.59.105.169:13414 corrupted, ban (ConsensusError(SortError)).
Mar 28 15:20:17.060 DEBG Requesting compact block 0565848e from 193.175.82.53:13414
Mar 28 15:20:18.033 INFO Client 193.175.82.53:13414 corrupted, ban (ConsensusError(SortError)).
```

Whether the full or compact block were requested does not seem to make a difference.

**Comment by ignopeverell** [comment]
This caused that machine to go on its own fork for a bit, then after a while sync kicked in and the _same_ block was finally accepted.

```
DEBG Received block 4aaf0da5 at 1748 from 45.63.88.120:13414, going to process.
DEBG pipe: process_block 4aaf0da5 at 1748 with 0 inputs, 1 outputs, 1 kernels
```

**Comment by ignopeverell** [comment]
@antiochp I've been looking through the block and transaction sorting code and can't see what would lead to this inconsistency. But you're more familiar with that part of the code, anything that would jump to mind?

**Comment by antiochp** [comment]
I can take a look at this - there is nothing obvious that would cause this to happen.

**Comment by antiochp** [comment]
The only other thing I can think of is `verify_sort_order()` checks that they are sorted based on calling `hash()` on each item (inputs/outputs/kernels).
Whereas `write_sorted()` during serialization sorts them based on the structs themselves.

So maybe there is a subtle difference in inputs, outputs or kernels where the object sort order is different to the sort order of the hashes.
I thought we had considered this and accounted for it previously - but maybe something changed.

I need to take another look through this code.
99% certain this is the issue after writing this down here.

**Comment by antiochp** [comment]
Ok I think the logs here are confusing as we are interleaving across multiple peers (in separate threads).

The issue is the short_ids in CompactBlock. This is _only_ happening when a peer sends a compact_block that contains multiple kernel ids (in short_id form).

In CompactBlock we maintain a vec of kern_ids - 
https://github.com/mimblewimble/grin/blob/c460f9876a4b11e709efcff763ffdaf8fbed9675/core/src/core/block.rs#L241

We ensure these are sorted here -
https://github.com/mimblewimble/grin/blob/c460f9876a4b11e709efcff763ffdaf8fbed9675/core/src/core/block.rs#L269

But we are using the natural sort order to do this (we are sorting the short_ids themselves).

On the receiving end we verify that they are actually sorted here - 
https://github.com/mimblewimble/grin/blob/c460f9876a4b11e709efcff763ffdaf8fbed9675/core/src/core/block.rs#L269

But `read_and_verify_sorted()` sorts a vec of `Writeable`, calling `hash()` on them, sorting based on the value of the hash.

`read_and_verify_sorted()` works as expected for full `inputs|outputs|kernels` but it does not work correctly for `short_ids` in compact_blocks in the current implementation.

I'm going to put a fix in for this shortly to ensure `short_ids` are sorted correctly.

@ignopeverell
